# AUTO-GENERATED by scripts/generate.mjs from spec/endpoints.json DO NOT EDIT.
# Regenerate with: node scripts/generate.mjs
from ._http import enc


class AuthResource:
    """Auth Account registration, password + passwordless sign-in, 2FA login and token refresh."""

    def __init__(self, client):
        self._c = client

    def register(self, body=None, **opts):
        """Register an account; returns the user plus an accessToken/refreshToken pair."""
        return self._c._request("POST", "/api/v1/auth/register", body=body, **opts)

    def login(self, body=None, **opts):
        """Log in with email + password; returns a JWT pair (or a 2FA challenge)."""
        return self._c._request("POST", "/api/v1/auth/login", body=body, **opts)

    def login_verify2fa(self, body=None, **opts):
        """Complete a 2FA login challenge; returns the JWT pair."""
        return self._c._request("POST", "/api/v1/auth/2fa-verify", body=body, **opts)

    def request_token(self, body=None, **opts):
        """Passwordless: email a buyer a 6-digit login code."""
        return self._c._request("POST", "/api/v1/auth/token/request", body=body, **opts)

    def exchange_token(self, body=None, **opts):
        """Passwordless: exchange email + 6-digit code for a JWT pair."""
        return self._c._request("POST", "/api/v1/auth/token/exchange", body=body, **opts)

    def refresh(self, body=None, **opts):
        """Refresh an expired access token (rotates the refresh token)."""
        return self._c._request("POST", "/api/v1/auth/refresh", body=body, **opts)

    def logout(self, body=None, **opts):
        """Revoke a refresh token."""
        return self._c._request("POST", "/api/v1/auth/logout", body=body, **opts)


class EventsResource:
    """Events (Public) Public event discovery and read, plus external ticket issuance."""

    def __init__(self, client):
        self._c = client

    def list(self, query=None, **opts):
        """List and search published public events (cursor-paginated). Filters: q, category, city, and the read-only facets productType (event|reservation|digital) and course=true (courses within digital)."""
        return self._c._request("GET", "/api/v1/events", query=query, **opts)

    def search(self, query=None, **opts):
        """Full-text + faceted event search. Same q/category/city/productType/course facets as events.list, plus date_from/date_to; each result carries category + read-only productType."""
        return self._c._request("GET", "/api/v1/search", query=query, **opts)

    def get(self, slug, query=None, **opts):
        """Event detail by slug (organizer info, schedule, active ticket types; carries category + read-only productType)."""
        return self._c._request("GET", "/api/v1/events/" + enc(slug), query=query, **opts)

    def tickets(self, id, query=None, **opts):
        """List an event's ticket types with live availability."""
        return self._c._request("GET", "/api/v1/events/" + enc(id) + "/tickets", query=query, **opts)

    def issue(self, event_id, body=None, **opts):
        """Issue tickets you sold elsewhere (developer-handled payment; 3% wallet fee on paid tickets)."""
        return self._c._request("POST", "/api/v1/events/" + enc(event_id) + "/issue", body=body, **opts)


class SeatingResource:
    """Seating (Public) Interactive venue seating: the buyer-facing seat map, live availability and temporary seat holds. Only events an organizer has attached a venue map to expose these (others 404 NO_SEATING). Buy seats by passing venueSeatIds on orders.create. No auth required."""

    def __init__(self, client):
        self._c = client

    def seatmap(self, event_id, query=None, **opts):
        """Get the seat map: sections, seats with x/y coordinates, stage/label elements, and the ticket type + price per section."""
        return self._c._request("GET", "/api/v1/public/events/" + enc(event_id) + "/seatmap", query=query, **opts)

    def seats(self, event_id, query=None, **opts):
        """Live seat availability snapshot { sold, blocked, held } any seat id not listed is available."""
        return self._c._request("GET", "/api/v1/public/events/" + enc(event_id) + "/seats", query=query, **opts)

    def live_url(self, event_id, query=None):
        """Server-Sent Events stream of live seat availability (a snapshot on connect, then seat_update events). (SSE returns the stream URL)."""
        return self._c._url("/api/v1/public/events/" + enc(event_id) + "/seats/live", query)

    def hold(self, event_id, body=None, **opts):
        """Hold (replace) the seats a buyer is selecting for an opaque holder token; returns { held, failed }."""
        return self._c._request("POST", "/api/v1/public/events/" + enc(event_id) + "/seats/hold", body=body, **opts)

    def release_hold(self, event_id, body=None, **opts):
        """Release a holder's seat holds (omit seatIds in the body to release all of them)."""
        return self._c._request("DELETE", "/api/v1/public/events/" + enc(event_id) + "/seats/hold", body=body, **opts)


class OrganizerResource:
    """Organizer Organizer surface: organization read, events, ticket types, schedule sessions, seating sections and promo codes."""

    def __init__(self, client):
        self._c = client

    def get_organization(self, id, query=None, **opts):
        """Get organization details and per-currency wallet balances."""
        return self._c._request("GET", "/api/v1/organizer/organizations/" + enc(id), query=query, **opts)

    def create_event(self, body=None, **opts):
        """Create a draft event."""
        return self._c._request("POST", "/api/v1/organizer/events", body=body, **opts)

    def update_event(self, id, body=None, **opts):
        """Partial-update an event."""
        return self._c._request("PUT", "/api/v1/organizer/events/" + enc(id), body=body, **opts)

    def publish_event(self, id, body=None, **opts):
        """Publish a draft event."""
        return self._c._request("POST", "/api/v1/organizer/events/" + enc(id) + "/publish", body=body, **opts)

    def unpublish_event(self, id, body=None, **opts):
        """Unpublish a published event back to draft."""
        return self._c._request("POST", "/api/v1/organizer/events/" + enc(id) + "/unpublish", body=body, **opts)

    def delete_event(self, id, body=None, **opts):
        """Cancel an event."""
        return self._c._request("DELETE", "/api/v1/organizer/events/" + enc(id), body=body, **opts)

    def create_ticket(self, id, body=None, **opts):
        """Create a ticket type."""
        return self._c._request("POST", "/api/v1/organizer/events/" + enc(id) + "/tickets", body=body, **opts)

    def schedule(self, id, query=None, **opts):
        """List schedule sessions (running order)."""
        return self._c._request("GET", "/api/v1/organizer/events/" + enc(id) + "/schedule", query=query, **opts)

    def create_schedule(self, id, body=None, **opts):
        """Add a schedule session."""
        return self._c._request("POST", "/api/v1/organizer/events/" + enc(id) + "/schedule", body=body, **opts)

    def update_schedule(self, id, session_id, body=None, **opts):
        """Update a schedule session."""
        return self._c._request("PUT", "/api/v1/organizer/events/" + enc(id) + "/schedule/" + enc(session_id), body=body, **opts)

    def delete_schedule(self, id, session_id, body=None, **opts):
        """Delete a schedule session."""
        return self._c._request("DELETE", "/api/v1/organizer/events/" + enc(id) + "/schedule/" + enc(session_id), body=body, **opts)

    def sections(self, id, query=None, **opts):
        """List seating/capacity sections."""
        return self._c._request("GET", "/api/v1/organizer/events/" + enc(id) + "/sections", query=query, **opts)

    def create_section(self, id, body=None, **opts):
        """Add a seating section."""
        return self._c._request("POST", "/api/v1/organizer/events/" + enc(id) + "/sections", body=body, **opts)

    def update_section(self, id, section_id, body=None, **opts):
        """Update a seating section."""
        return self._c._request("PUT", "/api/v1/organizer/events/" + enc(id) + "/sections/" + enc(section_id), body=body, **opts)

    def delete_section(self, id, section_id, body=None, **opts):
        """Delete a seating section."""
        return self._c._request("DELETE", "/api/v1/organizer/events/" + enc(id) + "/sections/" + enc(section_id), body=body, **opts)

    def venues(self, query=None, **opts):
        """Browse published venue seat maps you can attach to an event (interactive seating)."""
        return self._c._request("GET", "/api/v1/organizer/venues", query=query, **opts)

    def get_event_seating(self, id, query=None, **opts):
        """Get an event's interactive-seating setup: attached map, section→ticket-type pricing, and blocked/sold seats."""
        return self._c._request("GET", "/api/v1/organizer/events/" + enc(id) + "/seating", query=query, **opts)

    def attach_seating(self, id, body=None, **opts):
        """Attach a published venue map to the event (body: venueMapId, optional mode/holdTtlSeconds)."""
        return self._c._request("PUT", "/api/v1/organizer/events/" + enc(id) + "/seating", body=body, **opts)

    def detach_seating(self, id, body=None, **opts):
        """Remove interactive seating from the event (only before any seat sells)."""
        return self._c._request("DELETE", "/api/v1/organizer/events/" + enc(id) + "/seating", body=body, **opts)

    def set_seating_pricing(self, id, body=None, **opts):
        """Map each venue section to one of the event's ticket types (body: mappings:[{venueSectionId, ticketTypeId}])."""
        return self._c._request("PUT", "/api/v1/organizer/events/" + enc(id) + "/seating/pricing", body=body, **opts)

    def set_seating_blocks(self, id, body=None, **opts):
        """Block or unblock seats for the event (body: block:[seatId], unblock:[seatId])."""
        return self._c._request("POST", "/api/v1/organizer/events/" + enc(id) + "/seating/blocks", body=body, **opts)

    def promo_codes(self, query=None, **opts):
        """List promo codes (optionally filtered by event)."""
        return self._c._request("GET", "/api/v1/organizer/promo-codes", query=query, **opts)

    def create_promo_code(self, body=None, **opts):
        """Create a promo code."""
        return self._c._request("POST", "/api/v1/organizer/promo-codes", body=body, **opts)

    def update_promo_code(self, id, body=None, **opts):
        """Update a promo code."""
        return self._c._request("PUT", "/api/v1/organizer/promo-codes/" + enc(id), body=body, **opts)

    def delete_promo_code(self, id, body=None, **opts):
        """Delete or disable a promo code."""
        return self._c._request("DELETE", "/api/v1/organizer/promo-codes/" + enc(id), body=body, **opts)


class EventCustomizationResource:
    """Event page customization Per-event public-page theming and the “Good to know” FAQ."""

    def __init__(self, client):
        self._c = client

    def get(self, id, query=None, **opts):
        """Get an event's page customization (theme, layout, FAQ, SEO)."""
        return self._c._request("GET", "/api/v1/organizer/event-customization/" + enc(id), query=query, **opts)

    def update(self, id, body=None, **opts):
        """Update an event's page customization (incl. the FAQ list)."""
        return self._c._request("PUT", "/api/v1/organizer/event-customization/" + enc(id), body=body, **opts)


class TicketsResource:
    """Tickets Checkout-time ticket helpers."""

    def __init__(self, client):
        self._c = client

    def validate_promo(self, body=None, **opts):
        """Validate a promo code against a cart (read-only preview, does not consume a use)."""
        return self._c._request("POST", "/api/v1/tickets/promo/validate", body=body, **opts)


class OrdersResource:
    """Orders Carted checkout: create, read, pay, cancel."""

    def __init__(self, client):
        self._c = client

    def create(self, body=None, **opts):
        """Create an order (guest checkout needs only name + email)."""
        return self._c._request("POST", "/api/v1/orders", body=body, **opts)

    def get(self, id, query=None, **opts):
        """Get an order (pass ?token for guest reads)."""
        return self._c._request("GET", "/api/v1/orders/" + enc(id), query=query, **opts)

    def pay(self, id, body=None, **opts):
        """Initiate payment (provider: nowpayments | paystack | flutterwave)."""
        return self._c._request("POST", "/api/v1/orders/" + enc(id) + "/pay", body=body, **opts)

    def cancel(self, id, body=None, **opts):
        """Cancel an unpaid order and release held inventory."""
        return self._c._request("POST", "/api/v1/orders/" + enc(id) + "/cancel", body=body, **opts)


class PaymentsResource:
    """Payments Verify charges, read payment status, list crypto coins."""

    def __init__(self, client):
        self._c = client

    def verify(self, body=None, **opts):
        """Actively verify a payment with the provider and issue tickets (idempotent, poll-safe)."""
        return self._c._request("POST", "/api/v1/payments/verify", body=body, **opts)

    def get(self, order_id, query=None, **opts):
        """Read payment/order status and attempts (read-only)."""
        return self._c._request("GET", "/api/v1/payments/" + enc(order_id), query=query, **opts)

    def crypto_currencies(self, query=None, **opts):
        """List supported NOWPayments crypto coins (for the payCurrency value)."""
        return self._c._request("GET", "/api/v1/payments/crypto/currencies", query=query, **opts)


class CheckinResource:
    """Check-in Gate scanning, offline manifests + sync, live stats."""

    def __init__(self, client):
        self._c = client

    def scan(self, body=None, **opts):
        """Validate a QR, barcode or 6-character door code at the gate."""
        return self._c._request("POST", "/api/v1/checkin/scan", body=body, **opts)

    def manual(self, id, body=None, **opts):
        """Manually check in a typed ticket code."""
        return self._c._request("POST", "/api/v1/checkin/event/" + enc(id) + "/manual", body=body, **opts)

    def manifest(self, id, query=None, **opts):
        """Hashed guest-list manifest for offline scanning (pass ?since for a delta)."""
        return self._c._request("GET", "/api/v1/checkin/event/" + enc(id) + "/manifest", query=query, **opts)

    def batch(self, body=None, **opts):
        """Sync up to 500 queued offline scans."""
        return self._c._request("POST", "/api/v1/checkin/batch", body=body, **opts)

    def stats(self, id, query=None, **opts):
        """Check-in totals, capacity %, entry rate and per-gate breakdown."""
        return self._c._request("GET", "/api/v1/checkin/event/" + enc(id) + "/stats", query=query, **opts)

    def gate(self, id, gate, query=None, **opts):
        """Per-gate check-in stats slice."""
        return self._c._request("GET", "/api/v1/checkin/event/" + enc(id) + "/gate/" + enc(gate), query=query, **opts)

    def live_url(self, id, query=None):
        """Server-Sent Events stream a stats snapshot every 2 seconds. (SSE returns the stream URL)."""
        return self._c._url("/api/v1/checkin/event/" + enc(id) + "/live", query)


class CommunityResource:
    """Community Verified-attendee reviews, organizer follows/subscribers and event waitlists."""

    def __init__(self, client):
        self._c = client

    def submit_review(self, body=None, **opts):
        """Review an event (checked-in ticket holders only; ticketCode + email prove attendance)."""
        return self._c._request("POST", "/api/v1/community/reviews", body=body, **opts)

    def follow(self, org_id, body=None, **opts):
        """Follow an organizer (subscribe to new-event announcements)."""
        return self._c._request("POST", "/api/v1/community/orgs/" + enc(org_id) + "/follow", body=body, **opts)

    def followers(self, org_id, query=None, **opts):
        """List an organizer's subscribers (organizer auth)."""
        return self._c._request("GET", "/api/v1/community/orgs/" + enc(org_id) + "/followers", query=query, **opts)

    def remove_follower(self, org_id, follower_id, body=None, **opts):
        """Remove a subscriber (organizer auth)."""
        return self._c._request("DELETE", "/api/v1/community/orgs/" + enc(org_id) + "/followers/" + enc(follower_id), body=body, **opts)

    def join_waitlist(self, event_id, body=None, **opts):
        """Join an event waitlist (offers fire on cancellations)."""
        return self._c._request("POST", "/api/v1/community/events/" + enc(event_id) + "/waitlist", body=body, **opts)


class GrowthResource:
    """Growth (Organizer) Comp tickets, CSV import, broadcasts and attendee tags."""

    def __init__(self, client):
        self._c = client

    def mint_comps(self, event_id, body=None, **opts):
        """Bulk-mint and email complimentary tickets."""
        return self._c._request("POST", "/api/v1/organizer/growth/events/" + enc(event_id) + "/comps", body=body, **opts)

    def import_comps_csv(self, event_id, body=None, **opts):
        """Import attendees (comp tickets) from CSV."""
        return self._c._request("POST", "/api/v1/organizer/growth/events/" + enc(event_id) + "/comps/import-csv", body=body, **opts)

    def broadcast_event(self, event_id, body=None, **opts):
        """Email a broadcast to an event's attendees (replies thread to the organizer inbox)."""
        return self._c._request("POST", "/api/v1/organizer/growth/events/" + enc(event_id) + "/broadcast", body=body, **opts)

    def add_tags(self, body=None, **opts):
        """Tag attendees (additive; powers broadcast filters and CRM segments)."""
        return self._c._request("POST", "/api/v1/organizer/growth/tags", body=body, **opts)

    def remove_tag(self, body=None, **opts):
        """Remove an attendee tag."""
        return self._c._request("DELETE", "/api/v1/organizer/growth/tags", body=body, **opts)


class UsersResource:
    """Buyers The authenticated buyer: profile, ticket wallet, data export, refunds, reports and organizer messaging."""

    def __init__(self, client):
        self._c = client

    def me(self, query=None, **opts):
        """Current buyer profile."""
        return self._c._request("GET", "/api/v1/users/me", query=query, **opts)

    def tickets(self, query=None, **opts):
        """The buyer's ticket wallet (cursor-paginated)."""
        return self._c._request("GET", "/api/v1/users/me/tickets", query=query, **opts)

    def export(self, query=None, **opts):
        """GDPR data export one JSON download of everything on the account."""
        return self._c._request("GET", "/api/v1/users/me/export", query=query, **opts)

    def create_refund(self, body=None, **opts):
        """Request a refund for a ticket."""
        return self._c._request("POST", "/api/v1/users/me/refunds", body=body, **opts)

    def create_report(self, body=None, **opts):
        """File a report against an event or organizer."""
        return self._c._request("POST", "/api/v1/users/me/reports", body=body, **opts)

    def messages(self, query=None, **opts):
        """The buyer's message threads with organizers."""
        return self._c._request("GET", "/api/v1/users/me/messages", query=query, **opts)

    def send_ticket_message(self, ticket_id, body=None, **opts):
        """Message the organizer about a ticket (rate-limited)."""
        return self._c._request("POST", "/api/v1/users/me/tickets/" + enc(ticket_id) + "/message", body=body, **opts)


class CoursesResource:
    """Courses (Learner) The authenticated buyer's online-course learner surface: enrolled courses, lesson/course completion, the exam, and the completion certificate. Course content (paid lesson media, writeups, pins) is delivered only to enrolled ticket holders; media links returned here are short-lived signed /media URLs. Buyer auth (a ticket for the course) required."""

    def __init__(self, client):
        self._c = client

    def mine(self, query=None, **opts):
        """List the buyer's enrolled courses, each with course meta and a progress summary (started courses first). No lesson content."""
        return self._c._request("GET", "/api/v1/courses/mine", query=query, **opts)

    def get(self, event_id, query=None, **opts):
        """Get one course's full learner payload: meta + progress + lessons (syllabus, with completed flags and signed media) or a unified content block."""
        return self._c._request("GET", "/api/v1/courses/" + enc(event_id), query=query, **opts)

    def complete_lesson(self, event_id, index, body=None, **opts):
        """Mark a syllabus lesson complete (idempotent, zero-based index). Completing the last requirement finishes the course and may issue a certificate."""
        return self._c._request("POST", "/api/v1/courses/" + enc(event_id) + "/lessons/" + enc(index) + "/complete", body=body, **opts)

    def uncomplete_lesson(self, event_id, index, body=None, **opts):
        """Reverse a syllabus lesson completion (does not revoke an already-issued certificate)."""
        return self._c._request("DELETE", "/api/v1/courses/" + enc(event_id) + "/lessons/" + enc(index) + "/complete", body=body, **opts)

    def complete(self, event_id, body=None, **opts):
        """Complete a unified course (unified courses only): marks the single learning unit complete."""
        return self._c._request("POST", "/api/v1/courses/" + enc(event_id) + "/complete", body=body, **opts)

    def exam(self, event_id, query=None, **opts):
        """Get the course exam to take. Correct answers and explanations are stripped server-side."""
        return self._c._request("GET", "/api/v1/courses/" + enc(event_id) + "/exam", query=query, **opts)

    def submit_exam(self, event_id, body=None, **opts):
        """Submit the exam (body: answers:[{questionId, selectedIndex}]) for server-side grading; a pass drives completion + certificate issuance."""
        return self._c._request("POST", "/api/v1/courses/" + enc(event_id) + "/exam/submit", body=body, **opts)

    def certificate(self, event_id, query=None, **opts):
        """Download the issued completion certificate as a PDF (404 CERTIFICATE_NOT_ISSUED until earned)."""
        return self._c._request("GET", "/api/v1/courses/" + enc(event_id) + "/certificate", query=query, raw=True, **opts)


class IntegrationsResource:
    """API keys Manage your organization's own API keys (organizer owner/admin auth)."""

    def __init__(self, client):
        self._c = client

    def create_api_key(self, org_id, body=None, **opts):
        """Create an API key (plaintext secret returned exactly once)."""
        return self._c._request("POST", "/api/v1/organizer/integrations/org/" + enc(org_id) + "/api-keys", body=body, **opts)

    def list_api_keys(self, org_id, query=None, **opts):
        """List API keys (prefixes and metadata only, never the secret)."""
        return self._c._request("GET", "/api/v1/organizer/integrations/org/" + enc(org_id) + "/api-keys", query=query, **opts)

    def update_api_key(self, org_id, key_id, body=None, **opts):
        """Update a key (rename, pause, re-scope)."""
        return self._c._request("PUT", "/api/v1/organizer/integrations/org/" + enc(org_id) + "/api-keys/" + enc(key_id), body=body, **opts)

    def rotate_api_key(self, org_id, key_id, body=None, **opts):
        """Rotate a key's secret (new secret returned once; old one invalidated)."""
        return self._c._request("POST", "/api/v1/organizer/integrations/org/" + enc(org_id) + "/api-keys/" + enc(key_id) + "/rotate", body=body, **opts)

    def delete_api_key(self, org_id, key_id, body=None, **opts):
        """Revoke an API key."""
        return self._c._request("DELETE", "/api/v1/organizer/integrations/org/" + enc(org_id) + "/api-keys/" + enc(key_id), body=body, **opts)


class WebhooksResource:
    """Webhooks Register webhook endpoints, manage secrets, inspect and replay deliveries. (Use webhooks.verify() to validate inbound signatures.)"""

    def __init__(self, client):
        self._c = client

    def create(self, body=None, **opts):
        """Create a webhook endpoint (signing secret returned exactly once)."""
        return self._c._request("POST", "/api/v1/webhooks", body=body, **opts)

    def list(self, query=None, **opts):
        """List webhook endpoints."""
        return self._c._request("GET", "/api/v1/webhooks", query=query, **opts)

    def update(self, id, body=None, **opts):
        """Update a webhook endpoint."""
        return self._c._request("PUT", "/api/v1/webhooks/" + enc(id), body=body, **opts)

    def delete(self, id, body=None, **opts):
        """Delete a webhook endpoint."""
        return self._c._request("DELETE", "/api/v1/webhooks/" + enc(id), body=body, **opts)

    def test(self, id, body=None, **opts):
        """Send a signed test event to the endpoint."""
        return self._c._request("POST", "/api/v1/webhooks/" + enc(id) + "/test", body=body, **opts)

    def rotate_secret(self, id, body=None, **opts):
        """Rotate the signing secret (new secret returned once)."""
        return self._c._request("POST", "/api/v1/webhooks/" + enc(id) + "/rotate-secret", body=body, **opts)

    def deliveries(self, id, query=None, **opts):
        """List delivery attempts for an endpoint."""
        return self._c._request("GET", "/api/v1/webhooks/" + enc(id) + "/deliveries", query=query, **opts)

    def replay(self, id, body=None, **opts):
        """Replay a past delivery."""
        return self._c._request("POST", "/api/v1/webhooks/deliveries/" + enc(id) + "/replay", body=body, **opts)

    def catalog(self, query=None, **opts):
        """List every subscribable event type (no auth)."""
        return self._c._request("GET", "/api/v1/webhooks/catalog", query=query, **opts)


RESOURCES = {
    "auth": AuthResource,
    "events": EventsResource,
    "seating": SeatingResource,
    "organizer": OrganizerResource,
    "event_customization": EventCustomizationResource,
    "tickets": TicketsResource,
    "orders": OrdersResource,
    "payments": PaymentsResource,
    "checkin": CheckinResource,
    "community": CommunityResource,
    "growth": GrowthResource,
    "users": UsersResource,
    "courses": CoursesResource,
    "integrations": IntegrationsResource,
    "webhooks": WebhooksResource,
}
