// AUTO-GENERATED by scripts/generate.mjs from spec/endpoints.json DO NOT EDIT.
// Regenerate with: node scripts/generate.mjs

import type { RequestOptions } from './index';

/** Auth Account registration, password + passwordless sign-in, 2FA login and token refresh. */
export interface AuthNamespace {
  /** Register an account; returns the user plus an accessToken/refreshToken pair. */
  register(body?: any, opts?: RequestOptions): Promise<any>;
  /** Log in with email + password; returns a JWT pair (or a 2FA challenge). */
  login(body?: any, opts?: RequestOptions): Promise<any>;
  /** Complete a 2FA login challenge; returns the JWT pair. */
  loginVerify2fa(body?: any, opts?: RequestOptions): Promise<any>;
  /** Passwordless: email a buyer a 6-digit login code. */
  requestToken(body?: any, opts?: RequestOptions): Promise<any>;
  /** Passwordless: exchange email + 6-digit code for a JWT pair. */
  exchangeToken(body?: any, opts?: RequestOptions): Promise<any>;
  /** Refresh an expired access token (rotates the refresh token). */
  refresh(body?: any, opts?: RequestOptions): Promise<any>;
  /** Revoke a refresh token. */
  logout(body?: any, opts?: RequestOptions): Promise<any>;
}

/** Events (Public) Public event discovery and read, plus external ticket issuance. */
export interface EventsNamespace {
  /** List and search published public events (cursor-paginated). */
  list(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Event detail by slug (organizer info, schedule, active ticket types). */
  get(slug: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** List an event's ticket types with live availability. */
  tickets(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Issue tickets you sold elsewhere (developer-handled payment; 3% wallet fee on paid tickets). */
  issue(eventId: string, body?: any, opts?: RequestOptions): Promise<any>;
}

/** Organizer Organizer surface: organization read, events, ticket types, schedule sessions, seating sections and promo codes. */
export interface OrganizerNamespace {
  /** Get organization details and per-currency wallet balances. */
  getOrganization(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Create a draft event. */
  createEvent(body?: any, opts?: RequestOptions): Promise<any>;
  /** Partial-update an event. */
  updateEvent(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Publish a draft event. */
  publishEvent(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Unpublish a published event back to draft. */
  unpublishEvent(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Cancel an event. */
  deleteEvent(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Create a ticket type. */
  createTicket(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** List schedule sessions (running order). */
  schedule(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Add a schedule session. */
  createSchedule(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Update a schedule session. */
  updateSchedule(id: string, sessionId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Delete a schedule session. */
  deleteSchedule(id: string, sessionId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** List seating/capacity sections. */
  sections(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Add a seating section. */
  createSection(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Update a seating section. */
  updateSection(id: string, sectionId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Delete a seating section. */
  deleteSection(id: string, sectionId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** List promo codes (optionally filtered by event). */
  promoCodes(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Create a promo code. */
  createPromoCode(body?: any, opts?: RequestOptions): Promise<any>;
  /** Update a promo code. */
  updatePromoCode(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Delete or disable a promo code. */
  deletePromoCode(id: string, body?: any, opts?: RequestOptions): Promise<any>;
}

/** Event page customization Per-event public-page theming and the “Good to know” FAQ. */
export interface EventCustomizationNamespace {
  /** Get an event's page customization (theme, layout, FAQ, SEO). */
  get(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Update an event's page customization (incl. the FAQ list). */
  update(id: string, body?: any, opts?: RequestOptions): Promise<any>;
}

/** Tickets Checkout-time ticket helpers. */
export interface TicketsNamespace {
  /** Validate a promo code against a cart (read-only preview, does not consume a use). */
  validatePromo(body?: any, opts?: RequestOptions): Promise<any>;
}

/** Orders Carted checkout: create, read, pay, cancel. */
export interface OrdersNamespace {
  /** Create an order (guest checkout needs only name + email). */
  create(body?: any, opts?: RequestOptions): Promise<any>;
  /** Get an order (pass ?token for guest reads). */
  get(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Initiate payment (provider: nowpayments | paystack | flutterwave). */
  pay(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Cancel an unpaid order and release held inventory. */
  cancel(id: string, body?: any, opts?: RequestOptions): Promise<any>;
}

/** Payments Verify charges, read payment status, list crypto coins. */
export interface PaymentsNamespace {
  /** Actively verify a payment with the provider and issue tickets (idempotent, poll-safe). */
  verify(body?: any, opts?: RequestOptions): Promise<any>;
  /** Read payment/order status and attempts (read-only). */
  get(orderId: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** List supported NOWPayments crypto coins (for the payCurrency value). */
  cryptoCurrencies(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
}

/** Check-in Gate scanning, offline manifests + sync, live stats. */
export interface CheckinNamespace {
  /** Validate a QR, barcode or 6-character door code at the gate. */
  scan(body?: any, opts?: RequestOptions): Promise<any>;
  /** Manually check in a typed ticket code. */
  manual(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Hashed guest-list manifest for offline scanning (pass ?since for a delta). */
  manifest(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Sync up to 500 queued offline scans. */
  batch(body?: any, opts?: RequestOptions): Promise<any>;
  /** Check-in totals, capacity %, entry rate and per-gate breakdown. */
  stats(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Per-gate check-in stats slice. */
  gate(id: string, gate: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Server-Sent Events stream a stats snapshot every 2 seconds. (SSE returns the stream URL) */
  liveUrl(id: string, query?: Record<string, any>): string;
}

/** Community Verified-attendee reviews, organizer follows/subscribers and event waitlists. */
export interface CommunityNamespace {
  /** Review an event (checked-in ticket holders only; ticketCode + email prove attendance). */
  submitReview(body?: any, opts?: RequestOptions): Promise<any>;
  /** Follow an organizer (subscribe to new-event announcements). */
  follow(orgId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** List an organizer's subscribers (organizer auth). */
  followers(orgId: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Remove a subscriber (organizer auth). */
  removeFollower(orgId: string, followerId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Join an event waitlist (offers fire on cancellations). */
  joinWaitlist(eventId: string, body?: any, opts?: RequestOptions): Promise<any>;
}

/** Growth (Organizer) Comp tickets, CSV import, broadcasts and attendee tags. */
export interface GrowthNamespace {
  /** Bulk-mint and email complimentary tickets. */
  mintComps(eventId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Import attendees (comp tickets) from CSV. */
  importCompsCsv(eventId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Email a broadcast to an event's attendees (replies thread to the organizer inbox). */
  broadcastEvent(eventId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Tag attendees (additive; powers broadcast filters and CRM segments). */
  addTags(body?: any, opts?: RequestOptions): Promise<any>;
  /** Remove an attendee tag. */
  removeTag(body?: any, opts?: RequestOptions): Promise<any>;
}

/** Buyers The authenticated buyer: profile, ticket wallet, data export, refunds, reports and organizer messaging. */
export interface UsersNamespace {
  /** Current buyer profile. */
  me(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** The buyer's ticket wallet (cursor-paginated). */
  tickets(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** GDPR data export one JSON download of everything on the account. */
  export(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Request a refund for a ticket. */
  createRefund(body?: any, opts?: RequestOptions): Promise<any>;
  /** File a report against an event or organizer. */
  createReport(body?: any, opts?: RequestOptions): Promise<any>;
  /** The buyer's message threads with organizers. */
  messages(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Message the organizer about a ticket (rate-limited). */
  sendTicketMessage(ticketId: string, body?: any, opts?: RequestOptions): Promise<any>;
}

/** API keys Manage your organization's own API keys (organizer owner/admin auth). */
export interface IntegrationsNamespace {
  /** Create an API key (plaintext secret returned exactly once). */
  createApiKey(orgId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** List API keys (prefixes and metadata only, never the secret). */
  listApiKeys(orgId: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Update a key (rename, pause, re-scope). */
  updateApiKey(orgId: string, keyId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Rotate a key's secret (new secret returned once; old one invalidated). */
  rotateApiKey(orgId: string, keyId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Revoke an API key. */
  deleteApiKey(orgId: string, keyId: string, body?: any, opts?: RequestOptions): Promise<any>;
}

/** Webhooks Register webhook endpoints, manage secrets, inspect and replay deliveries. (Use webhooks.verify() to validate inbound signatures.) */
export interface WebhooksNamespace {
  /** Create a webhook endpoint (signing secret returned exactly once). */
  create(body?: any, opts?: RequestOptions): Promise<any>;
  /** List webhook endpoints. */
  list(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Update a webhook endpoint. */
  update(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Delete a webhook endpoint. */
  delete(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Send a signed test event to the endpoint. */
  test(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Rotate the signing secret (new secret returned once). */
  rotateSecret(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** List delivery attempts for an endpoint. */
  deliveries(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Replay a past delivery. */
  replay(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** List every subscribable event type (no auth). */
  catalog(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
}

/** All resource namespaces attached to a ZataboxClient. */
export interface ResourceNamespaces {
  auth: AuthNamespace;
  events: EventsNamespace;
  organizer: OrganizerNamespace;
  eventCustomization: EventCustomizationNamespace;
  tickets: TicketsNamespace;
  orders: OrdersNamespace;
  payments: PaymentsNamespace;
  checkin: CheckinNamespace;
  community: CommunityNamespace;
  growth: GrowthNamespace;
  users: UsersNamespace;
  integrations: IntegrationsNamespace;
  webhooks: WebhooksNamespace;
}
