// AUTO-GENERATED by scripts/generate.mjs from spec/endpoints.json DO NOT EDIT.
// Regenerate with: node scripts/generate.mjs

import type { RequestOptions, BinaryResponse } from './index';

/** Auth Account registration, password + passwordless sign-in, 2FA login and token refresh. */
export interface AuthNamespace {
  /** Register an account; returns the user plus an accessToken/refreshToken pair. */
  register(body?: any, opts?: RequestOptions): Promise<any>;
  /** Log in with email + password; returns a JWT pair (or a 2FA challenge). */
  login(body?: any, opts?: RequestOptions): Promise<any>;
  /** Complete a 2FA login challenge; returns the JWT pair. */
  loginVerify2fa(body?: any, opts?: RequestOptions): Promise<any>;
  /** Passwordless: email a buyer a 6-digit login code. */
  requestToken(body?: any, opts?: RequestOptions): Promise<any>;
  /** Passwordless: exchange email + 6-digit code for a JWT pair. */
  exchangeToken(body?: any, opts?: RequestOptions): Promise<any>;
  /** Refresh an expired access token (rotates the refresh token). */
  refresh(body?: any, opts?: RequestOptions): Promise<any>;
  /** Revoke a refresh token. */
  logout(body?: any, opts?: RequestOptions): Promise<any>;
}

/** Events (Public) Public event discovery and read, plus external ticket issuance. */
export interface EventsNamespace {
  /** List and search published public events (cursor-paginated). Filters: q, category, city, and the read-only facets productType (event|reservation|digital) and course=true (courses within digital). */
  list(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Full-text + faceted event search. Same q/category/city/productType/course facets as events.list, plus date_from/date_to; each result carries category + read-only productType. */
  search(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Event detail by slug (organizer info, schedule, active ticket types; carries category + read-only productType). */
  get(slug: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** List an event's ticket types with live availability. */
  tickets(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Issue tickets you sold elsewhere (developer-handled payment; 3% wallet fee on paid tickets). */
  issue(eventId: string, body?: any, opts?: RequestOptions): Promise<any>;
}

/** Seating (Public) Interactive venue seating: the buyer-facing seat map, live availability and temporary seat holds. Only events an organizer has attached a venue map to expose these (others 404 NO_SEATING). Buy seats by passing venueSeatIds on orders.create. No auth required. */
export interface SeatingNamespace {
  /** Get the seat map: sections, seats with x/y coordinates, stage/label elements, and the ticket type + price per section. */
  seatmap(eventId: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Live seat availability snapshot { sold, blocked, held } any seat id not listed is available. */
  seats(eventId: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Server-Sent Events stream of live seat availability (a snapshot on connect, then seat_update events). (SSE returns the stream URL) */
  liveUrl(eventId: string, query?: Record<string, any>): string;
  /** Hold (replace) the seats a buyer is selecting for an opaque holder token; returns { held, failed }. */
  hold(eventId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Release a holder's seat holds (omit seatIds in the body to release all of them). */
  releaseHold(eventId: string, body?: any, opts?: RequestOptions): Promise<any>;
}

/** Organizer Organizer surface: organization read, events, ticket types, schedule sessions, seating sections and promo codes. */
export interface OrganizerNamespace {
  /** Get organization details and per-currency wallet balances. */
  getOrganization(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Create a draft event. */
  createEvent(body?: any, opts?: RequestOptions): Promise<any>;
  /** Partial-update an event. */
  updateEvent(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Publish a draft event. */
  publishEvent(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Unpublish a published event back to draft. */
  unpublishEvent(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Cancel an event. */
  deleteEvent(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Create a ticket type. */
  createTicket(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** List schedule sessions (running order). */
  schedule(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Add a schedule session. */
  createSchedule(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Update a schedule session. */
  updateSchedule(id: string, sessionId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Delete a schedule session. */
  deleteSchedule(id: string, sessionId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** List seating/capacity sections. */
  sections(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Add a seating section. */
  createSection(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Update a seating section. */
  updateSection(id: string, sectionId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Delete a seating section. */
  deleteSection(id: string, sectionId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Browse published venue seat maps you can attach to an event (interactive seating). */
  venues(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Get an event's interactive-seating setup: attached map, section→ticket-type pricing, and blocked/sold seats. */
  getEventSeating(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Attach a published venue map to the event (body: venueMapId, optional mode/holdTtlSeconds). */
  attachSeating(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Remove interactive seating from the event (only before any seat sells). */
  detachSeating(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Map each venue section to one of the event's ticket types (body: mappings:[{venueSectionId, ticketTypeId}]). */
  setSeatingPricing(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Block or unblock seats for the event (body: block:[seatId], unblock:[seatId]). */
  setSeatingBlocks(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** List promo codes (optionally filtered by event). */
  promoCodes(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Create a promo code. */
  createPromoCode(body?: any, opts?: RequestOptions): Promise<any>;
  /** Update a promo code. */
  updatePromoCode(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Delete or disable a promo code. */
  deletePromoCode(id: string, body?: any, opts?: RequestOptions): Promise<any>;
}

/** Event page customization Per-event public-page theming and the “Good to know” FAQ. */
export interface EventCustomizationNamespace {
  /** Get an event's page customization (theme, layout, FAQ, SEO). */
  get(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Update an event's page customization (incl. the FAQ list). */
  update(id: string, body?: any, opts?: RequestOptions): Promise<any>;
}

/** Tickets Checkout-time ticket helpers. */
export interface TicketsNamespace {
  /** Validate a promo code against a cart (read-only preview, does not consume a use). */
  validatePromo(body?: any, opts?: RequestOptions): Promise<any>;
}

/** Orders Carted checkout: create, read, pay, cancel. */
export interface OrdersNamespace {
  /** Create an order (guest checkout needs only name + email). */
  create(body?: any, opts?: RequestOptions): Promise<any>;
  /** Get an order (pass ?token for guest reads). */
  get(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Initiate payment (provider: nowpayments | paystack | flutterwave). */
  pay(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Cancel an unpaid order and release held inventory. */
  cancel(id: string, body?: any, opts?: RequestOptions): Promise<any>;
}

/** Payments Verify charges, read payment status, list crypto coins. */
export interface PaymentsNamespace {
  /** Actively verify a payment with the provider and issue tickets (idempotent, poll-safe). */
  verify(body?: any, opts?: RequestOptions): Promise<any>;
  /** Read payment/order status and attempts (read-only). */
  get(orderId: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** List supported NOWPayments crypto coins (for the payCurrency value). */
  cryptoCurrencies(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
}

/** Check-in Gate scanning, offline manifests + sync, live stats. */
export interface CheckinNamespace {
  /** Validate a QR, barcode or 6-character door code at the gate. */
  scan(body?: any, opts?: RequestOptions): Promise<any>;
  /** Manually check in a typed ticket code. */
  manual(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Hashed guest-list manifest for offline scanning (pass ?since for a delta). */
  manifest(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Sync up to 500 queued offline scans. */
  batch(body?: any, opts?: RequestOptions): Promise<any>;
  /** Check-in totals, capacity %, entry rate and per-gate breakdown. */
  stats(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Per-gate check-in stats slice. */
  gate(id: string, gate: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Server-Sent Events stream a stats snapshot every 2 seconds. (SSE returns the stream URL) */
  liveUrl(id: string, query?: Record<string, any>): string;
}

/** Community Verified-attendee reviews, organizer follows/subscribers and event waitlists. */
export interface CommunityNamespace {
  /** Review an event (checked-in ticket holders only; ticketCode + email prove attendance). */
  submitReview(body?: any, opts?: RequestOptions): Promise<any>;
  /** Follow an organizer (subscribe to new-event announcements). */
  follow(orgId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** List an organizer's subscribers (organizer auth). */
  followers(orgId: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Remove a subscriber (organizer auth). */
  removeFollower(orgId: string, followerId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Join an event waitlist (offers fire on cancellations). */
  joinWaitlist(eventId: string, body?: any, opts?: RequestOptions): Promise<any>;
}

/** Growth (Organizer) Comp tickets, CSV import, broadcasts and attendee tags. */
export interface GrowthNamespace {
  /** Bulk-mint and email complimentary tickets. */
  mintComps(eventId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Import attendees (comp tickets) from CSV. */
  importCompsCsv(eventId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Email a broadcast to an event's attendees (replies thread to the organizer inbox). */
  broadcastEvent(eventId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Tag attendees (additive; powers broadcast filters and CRM segments). */
  addTags(body?: any, opts?: RequestOptions): Promise<any>;
  /** Remove an attendee tag. */
  removeTag(body?: any, opts?: RequestOptions): Promise<any>;
}

/** Buyers The authenticated buyer: profile, ticket wallet, data export, refunds, reports and organizer messaging. */
export interface UsersNamespace {
  /** Current buyer profile. */
  me(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** The buyer's ticket wallet (cursor-paginated). */
  tickets(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** GDPR data export one JSON download of everything on the account. */
  export(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Request a refund for a ticket. */
  createRefund(body?: any, opts?: RequestOptions): Promise<any>;
  /** File a report against an event or organizer. */
  createReport(body?: any, opts?: RequestOptions): Promise<any>;
  /** The buyer's message threads with organizers. */
  messages(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Message the organizer about a ticket (rate-limited). */
  sendTicketMessage(ticketId: string, body?: any, opts?: RequestOptions): Promise<any>;
}

/** Courses (Learner) The authenticated buyer's online-course learner surface: enrolled courses, lesson/course completion, the exam, and the completion certificate. Course content (paid lesson media, writeups, pins) is delivered only to enrolled ticket holders; media links returned here are short-lived signed /media URLs. Buyer auth (a ticket for the course) required. */
export interface CoursesNamespace {
  /** List the buyer's enrolled courses, each with course meta and a progress summary (started courses first). No lesson content. */
  mine(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Get one course's full learner payload: meta + progress + lessons (syllabus, with completed flags and signed media) or a unified content block. */
  get(eventId: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Mark a syllabus lesson complete (idempotent, zero-based index). Completing the last requirement finishes the course and may issue a certificate. */
  completeLesson(eventId: string, index: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Reverse a syllabus lesson completion (does not revoke an already-issued certificate). */
  uncompleteLesson(eventId: string, index: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Complete a unified course (unified courses only): marks the single learning unit complete. */
  complete(eventId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Get the course exam to take. Correct answers and explanations are stripped server-side. */
  exam(eventId: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Submit the exam (body: answers:[{questionId, selectedIndex}]) for server-side grading; a pass drives completion + certificate issuance. */
  submitExam(eventId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Download the issued completion certificate as a PDF (404 CERTIFICATE_NOT_ISSUED until earned). */
  certificate(eventId: string, query?: Record<string, any>, opts?: RequestOptions): Promise<BinaryResponse>;
}

/** API keys Manage your organization's own API keys (organizer owner/admin auth). */
export interface IntegrationsNamespace {
  /** Create an API key (plaintext secret returned exactly once). */
  createApiKey(orgId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** List API keys (prefixes and metadata only, never the secret). */
  listApiKeys(orgId: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Update a key (rename, pause, re-scope). */
  updateApiKey(orgId: string, keyId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Rotate a key's secret (new secret returned once; old one invalidated). */
  rotateApiKey(orgId: string, keyId: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Revoke an API key. */
  deleteApiKey(orgId: string, keyId: string, body?: any, opts?: RequestOptions): Promise<any>;
}

/** Webhooks Register webhook endpoints, manage secrets, inspect and replay deliveries. (Use webhooks.verify() to validate inbound signatures.) */
export interface WebhooksNamespace {
  /** Create a webhook endpoint (signing secret returned exactly once). */
  create(body?: any, opts?: RequestOptions): Promise<any>;
  /** List webhook endpoints. */
  list(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Update a webhook endpoint. */
  update(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Delete a webhook endpoint. */
  delete(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Send a signed test event to the endpoint. */
  test(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** Rotate the signing secret (new secret returned once). */
  rotateSecret(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** List delivery attempts for an endpoint. */
  deliveries(id: string, query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
  /** Replay a past delivery. */
  replay(id: string, body?: any, opts?: RequestOptions): Promise<any>;
  /** List every subscribable event type (no auth). */
  catalog(query?: Record<string, any>, opts?: RequestOptions): Promise<any>;
}

/** All resource namespaces attached to a ZataboxClient. */
export interface ResourceNamespaces {
  auth: AuthNamespace;
  events: EventsNamespace;
  seating: SeatingNamespace;
  organizer: OrganizerNamespace;
  eventCustomization: EventCustomizationNamespace;
  tickets: TicketsNamespace;
  orders: OrdersNamespace;
  payments: PaymentsNamespace;
  checkin: CheckinNamespace;
  community: CommunityNamespace;
  growth: GrowthNamespace;
  users: UsersNamespace;
  courses: CoursesNamespace;
  integrations: IntegrationsNamespace;
  webhooks: WebhooksNamespace;
}
