// AUTO-GENERATED by scripts/generate.mjs from spec/endpoints.json DO NOT EDIT.
// Regenerate with: node scripts/generate.mjs

package zatabox

import (
	"context"
	"encoding/json"
)

// services bundles every resource namespace; embedded in Client.
type services struct {
	Auth *AuthService
	Events *EventsService
	Seating *SeatingService
	Organizer *OrganizerService
	EventCustomization *EventCustomizationService
	Tickets *TicketsService
	Orders *OrdersService
	Payments *PaymentsService
	Checkin *CheckinService
	Community *CommunityService
	Growth *GrowthService
	Users *UsersService
	Courses *CoursesService
	Integrations *IntegrationsService
	Webhooks *WebhooksService
}

func (c *Client) initServices() {
	c.Auth = &AuthService{c: c}
	c.Events = &EventsService{c: c}
	c.Seating = &SeatingService{c: c}
	c.Organizer = &OrganizerService{c: c}
	c.EventCustomization = &EventCustomizationService{c: c}
	c.Tickets = &TicketsService{c: c}
	c.Orders = &OrdersService{c: c}
	c.Payments = &PaymentsService{c: c}
	c.Checkin = &CheckinService{c: c}
	c.Community = &CommunityService{c: c}
	c.Growth = &GrowthService{c: c}
	c.Users = &UsersService{c: c}
	c.Courses = &CoursesService{c: c}
	c.Integrations = &IntegrationsService{c: c}
	c.Webhooks = &WebhooksService{c: c}
}

// AuthService Auth: Account registration, password + passwordless sign-in, 2FA login and token refresh.
type AuthService struct{ c *Client }

// Register Register an account; returns the user plus an accessToken/refreshToken pair.
func (s *AuthService) Register(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/auth/register", opts)
}

// Login Log in with email + password; returns a JWT pair (or a 2FA challenge).
func (s *AuthService) Login(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/auth/login", opts)
}

// LoginVerify2fa Complete a 2FA login challenge; returns the JWT pair.
func (s *AuthService) LoginVerify2fa(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/auth/2fa-verify", opts)
}

// RequestToken Passwordless: email a buyer a 6-digit login code.
func (s *AuthService) RequestToken(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/auth/token/request", opts)
}

// ExchangeToken Passwordless: exchange email + 6-digit code for a JWT pair.
func (s *AuthService) ExchangeToken(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/auth/token/exchange", opts)
}

// Refresh Refresh an expired access token (rotates the refresh token).
func (s *AuthService) Refresh(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/auth/refresh", opts)
}

// Logout Revoke a refresh token.
func (s *AuthService) Logout(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/auth/logout", opts)
}

// EventsService Events (Public): Public event discovery and read, plus external ticket issuance.
type EventsService struct{ c *Client }

// List List and search published public events (cursor-paginated). Filters: q, category, city, and the read-only facets productType (event|reservation|digital) and course=true (courses within digital).
func (s *EventsService) List(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/events", opts)
}

// Search Full-text + faceted event search. Same q/category/city/productType/course facets as events.list, plus date_from/date_to; each result carries category + read-only productType.
func (s *EventsService) Search(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/search", opts)
}

// Get Event detail by slug (organizer info, schedule, active ticket types; carries category + read-only productType).
func (s *EventsService) Get(ctx context.Context, slug string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/events/" + enc(slug), opts)
}

// Tickets List an event's ticket types with live availability.
func (s *EventsService) Tickets(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/events/" + enc(id) + "/tickets", opts)
}

// Issue Issue tickets you sold elsewhere (developer-handled payment; 3% wallet fee on paid tickets).
func (s *EventsService) Issue(ctx context.Context, eventId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/events/" + enc(eventId) + "/issue", opts)
}

// SeatingService Seating (Public): Interactive venue seating: the buyer-facing seat map, live availability and temporary seat holds. Only events an organizer has attached a venue map to expose these (others 404 NO_SEATING). Buy seats by passing venueSeatIds on orders.create. No auth required.
type SeatingService struct{ c *Client }

// Seatmap Get the seat map: sections, seats with x/y coordinates, stage/label elements, and the ticket type + price per section.
func (s *SeatingService) Seatmap(ctx context.Context, eventId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/public/events/" + enc(eventId) + "/seatmap", opts)
}

// Seats Live seat availability snapshot { sold, blocked, held } any seat id not listed is available.
func (s *SeatingService) Seats(ctx context.Context, eventId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/public/events/" + enc(eventId) + "/seats", opts)
}

// LiveURL Server-Sent Events stream of live seat availability (a snapshot on connect, then seat_update events). (SSE; returns the stream URL).
func (s *SeatingService) LiveURL(eventId string, queryArgs ...map[string]interface{}) string {
	return s.c.url("/api/v1/public/events/" + enc(eventId) + "/seats/live", firstQuery(queryArgs))
}

// Hold Hold (replace) the seats a buyer is selecting for an opaque holder token; returns { held, failed }.
func (s *SeatingService) Hold(ctx context.Context, eventId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/public/events/" + enc(eventId) + "/seats/hold", opts)
}

// ReleaseHold Release a holder's seat holds (omit seatIds in the body to release all of them).
func (s *SeatingService) ReleaseHold(ctx context.Context, eventId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "DELETE", "/api/v1/public/events/" + enc(eventId) + "/seats/hold", opts)
}

// OrganizerService Organizer: Organizer surface: organization read, events, ticket types, schedule sessions, seating sections and promo codes.
type OrganizerService struct{ c *Client }

// GetOrganization Get organization details and per-currency wallet balances.
func (s *OrganizerService) GetOrganization(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/organizer/organizations/" + enc(id), opts)
}

// CreateEvent Create a draft event.
func (s *OrganizerService) CreateEvent(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/organizer/events", opts)
}

// UpdateEvent Partial-update an event.
func (s *OrganizerService) UpdateEvent(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "PUT", "/api/v1/organizer/events/" + enc(id), opts)
}

// PublishEvent Publish a draft event.
func (s *OrganizerService) PublishEvent(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/organizer/events/" + enc(id) + "/publish", opts)
}

// UnpublishEvent Unpublish a published event back to draft.
func (s *OrganizerService) UnpublishEvent(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/organizer/events/" + enc(id) + "/unpublish", opts)
}

// DeleteEvent Cancel an event.
func (s *OrganizerService) DeleteEvent(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "DELETE", "/api/v1/organizer/events/" + enc(id), opts)
}

// CreateTicket Create a ticket type.
func (s *OrganizerService) CreateTicket(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/organizer/events/" + enc(id) + "/tickets", opts)
}

// Schedule List schedule sessions (running order).
func (s *OrganizerService) Schedule(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/organizer/events/" + enc(id) + "/schedule", opts)
}

// CreateSchedule Add a schedule session.
func (s *OrganizerService) CreateSchedule(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/organizer/events/" + enc(id) + "/schedule", opts)
}

// UpdateSchedule Update a schedule session.
func (s *OrganizerService) UpdateSchedule(ctx context.Context, id string, sessionId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "PUT", "/api/v1/organizer/events/" + enc(id) + "/schedule/" + enc(sessionId), opts)
}

// DeleteSchedule Delete a schedule session.
func (s *OrganizerService) DeleteSchedule(ctx context.Context, id string, sessionId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "DELETE", "/api/v1/organizer/events/" + enc(id) + "/schedule/" + enc(sessionId), opts)
}

// Sections List seating/capacity sections.
func (s *OrganizerService) Sections(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/organizer/events/" + enc(id) + "/sections", opts)
}

// CreateSection Add a seating section.
func (s *OrganizerService) CreateSection(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/organizer/events/" + enc(id) + "/sections", opts)
}

// UpdateSection Update a seating section.
func (s *OrganizerService) UpdateSection(ctx context.Context, id string, sectionId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "PUT", "/api/v1/organizer/events/" + enc(id) + "/sections/" + enc(sectionId), opts)
}

// DeleteSection Delete a seating section.
func (s *OrganizerService) DeleteSection(ctx context.Context, id string, sectionId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "DELETE", "/api/v1/organizer/events/" + enc(id) + "/sections/" + enc(sectionId), opts)
}

// Venues Browse published venue seat maps you can attach to an event (interactive seating).
func (s *OrganizerService) Venues(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/organizer/venues", opts)
}

// GetEventSeating Get an event's interactive-seating setup: attached map, section→ticket-type pricing, and blocked/sold seats.
func (s *OrganizerService) GetEventSeating(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/organizer/events/" + enc(id) + "/seating", opts)
}

// AttachSeating Attach a published venue map to the event (body: venueMapId, optional mode/holdTtlSeconds).
func (s *OrganizerService) AttachSeating(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "PUT", "/api/v1/organizer/events/" + enc(id) + "/seating", opts)
}

// DetachSeating Remove interactive seating from the event (only before any seat sells).
func (s *OrganizerService) DetachSeating(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "DELETE", "/api/v1/organizer/events/" + enc(id) + "/seating", opts)
}

// SetSeatingPricing Map each venue section to one of the event's ticket types (body: mappings:[{venueSectionId, ticketTypeId}]).
func (s *OrganizerService) SetSeatingPricing(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "PUT", "/api/v1/organizer/events/" + enc(id) + "/seating/pricing", opts)
}

// SetSeatingBlocks Block or unblock seats for the event (body: block:[seatId], unblock:[seatId]).
func (s *OrganizerService) SetSeatingBlocks(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/organizer/events/" + enc(id) + "/seating/blocks", opts)
}

// PromoCodes List promo codes (optionally filtered by event).
func (s *OrganizerService) PromoCodes(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/organizer/promo-codes", opts)
}

// CreatePromoCode Create a promo code.
func (s *OrganizerService) CreatePromoCode(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/organizer/promo-codes", opts)
}

// UpdatePromoCode Update a promo code.
func (s *OrganizerService) UpdatePromoCode(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "PUT", "/api/v1/organizer/promo-codes/" + enc(id), opts)
}

// DeletePromoCode Delete or disable a promo code.
func (s *OrganizerService) DeletePromoCode(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "DELETE", "/api/v1/organizer/promo-codes/" + enc(id), opts)
}

// EventCustomizationService Event page customization: Per-event public-page theming and the “Good to know” FAQ.
type EventCustomizationService struct{ c *Client }

// Get Get an event's page customization (theme, layout, FAQ, SEO).
func (s *EventCustomizationService) Get(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/organizer/event-customization/" + enc(id), opts)
}

// Update Update an event's page customization (incl. the FAQ list).
func (s *EventCustomizationService) Update(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "PUT", "/api/v1/organizer/event-customization/" + enc(id), opts)
}

// TicketsService Tickets: Checkout-time ticket helpers.
type TicketsService struct{ c *Client }

// ValidatePromo Validate a promo code against a cart (read-only preview, does not consume a use).
func (s *TicketsService) ValidatePromo(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/tickets/promo/validate", opts)
}

// OrdersService Orders: Carted checkout: create, read, pay, cancel.
type OrdersService struct{ c *Client }

// Create Create an order (guest checkout needs only name + email).
func (s *OrdersService) Create(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/orders", opts)
}

// Get Get an order (pass ?token for guest reads).
func (s *OrdersService) Get(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/orders/" + enc(id), opts)
}

// Pay Initiate payment (provider: nowpayments | paystack | flutterwave).
func (s *OrdersService) Pay(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/orders/" + enc(id) + "/pay", opts)
}

// Cancel Cancel an unpaid order and release held inventory.
func (s *OrdersService) Cancel(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/orders/" + enc(id) + "/cancel", opts)
}

// PaymentsService Payments: Verify charges, read payment status, list crypto coins.
type PaymentsService struct{ c *Client }

// Verify Actively verify a payment with the provider and issue tickets (idempotent, poll-safe).
func (s *PaymentsService) Verify(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/payments/verify", opts)
}

// Get Read payment/order status and attempts (read-only).
func (s *PaymentsService) Get(ctx context.Context, orderId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/payments/" + enc(orderId), opts)
}

// CryptoCurrencies List supported NOWPayments crypto coins (for the payCurrency value).
func (s *PaymentsService) CryptoCurrencies(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/payments/crypto/currencies", opts)
}

// CheckinService Check-in: Gate scanning, offline manifests + sync, live stats.
type CheckinService struct{ c *Client }

// Scan Validate a QR, barcode or 6-character door code at the gate.
func (s *CheckinService) Scan(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/checkin/scan", opts)
}

// Manual Manually check in a typed ticket code.
func (s *CheckinService) Manual(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/checkin/event/" + enc(id) + "/manual", opts)
}

// Manifest Hashed guest-list manifest for offline scanning (pass ?since for a delta).
func (s *CheckinService) Manifest(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/checkin/event/" + enc(id) + "/manifest", opts)
}

// Batch Sync up to 500 queued offline scans.
func (s *CheckinService) Batch(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/checkin/batch", opts)
}

// Stats Check-in totals, capacity %, entry rate and per-gate breakdown.
func (s *CheckinService) Stats(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/checkin/event/" + enc(id) + "/stats", opts)
}

// Gate Per-gate check-in stats slice.
func (s *CheckinService) Gate(ctx context.Context, id string, gate string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/checkin/event/" + enc(id) + "/gate/" + enc(gate), opts)
}

// LiveURL Server-Sent Events stream a stats snapshot every 2 seconds. (SSE; returns the stream URL).
func (s *CheckinService) LiveURL(id string, queryArgs ...map[string]interface{}) string {
	return s.c.url("/api/v1/checkin/event/" + enc(id) + "/live", firstQuery(queryArgs))
}

// CommunityService Community: Verified-attendee reviews, organizer follows/subscribers and event waitlists.
type CommunityService struct{ c *Client }

// SubmitReview Review an event (checked-in ticket holders only; ticketCode + email prove attendance).
func (s *CommunityService) SubmitReview(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/community/reviews", opts)
}

// Follow Follow an organizer (subscribe to new-event announcements).
func (s *CommunityService) Follow(ctx context.Context, orgId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/community/orgs/" + enc(orgId) + "/follow", opts)
}

// Followers List an organizer's subscribers (organizer auth).
func (s *CommunityService) Followers(ctx context.Context, orgId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/community/orgs/" + enc(orgId) + "/followers", opts)
}

// RemoveFollower Remove a subscriber (organizer auth).
func (s *CommunityService) RemoveFollower(ctx context.Context, orgId string, followerId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "DELETE", "/api/v1/community/orgs/" + enc(orgId) + "/followers/" + enc(followerId), opts)
}

// JoinWaitlist Join an event waitlist (offers fire on cancellations).
func (s *CommunityService) JoinWaitlist(ctx context.Context, eventId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/community/events/" + enc(eventId) + "/waitlist", opts)
}

// GrowthService Growth (Organizer): Comp tickets, CSV import, broadcasts and attendee tags.
type GrowthService struct{ c *Client }

// MintComps Bulk-mint and email complimentary tickets.
func (s *GrowthService) MintComps(ctx context.Context, eventId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/organizer/growth/events/" + enc(eventId) + "/comps", opts)
}

// ImportCompsCsv Import attendees (comp tickets) from CSV.
func (s *GrowthService) ImportCompsCsv(ctx context.Context, eventId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/organizer/growth/events/" + enc(eventId) + "/comps/import-csv", opts)
}

// BroadcastEvent Email a broadcast to an event's attendees (replies thread to the organizer inbox).
func (s *GrowthService) BroadcastEvent(ctx context.Context, eventId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/organizer/growth/events/" + enc(eventId) + "/broadcast", opts)
}

// AddTags Tag attendees (additive; powers broadcast filters and CRM segments).
func (s *GrowthService) AddTags(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/organizer/growth/tags", opts)
}

// RemoveTag Remove an attendee tag.
func (s *GrowthService) RemoveTag(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "DELETE", "/api/v1/organizer/growth/tags", opts)
}

// UsersService Buyers: The authenticated buyer: profile, ticket wallet, data export, refunds, reports and organizer messaging.
type UsersService struct{ c *Client }

// Me Current buyer profile.
func (s *UsersService) Me(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/users/me", opts)
}

// Tickets The buyer's ticket wallet (cursor-paginated).
func (s *UsersService) Tickets(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/users/me/tickets", opts)
}

// Export GDPR data export one JSON download of everything on the account.
func (s *UsersService) Export(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/users/me/export", opts)
}

// CreateRefund Request a refund for a ticket.
func (s *UsersService) CreateRefund(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/users/me/refunds", opts)
}

// CreateReport File a report against an event or organizer.
func (s *UsersService) CreateReport(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/users/me/reports", opts)
}

// Messages The buyer's message threads with organizers.
func (s *UsersService) Messages(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/users/me/messages", opts)
}

// SendTicketMessage Message the organizer about a ticket (rate-limited).
func (s *UsersService) SendTicketMessage(ctx context.Context, ticketId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/users/me/tickets/" + enc(ticketId) + "/message", opts)
}

// CoursesService Courses (Learner): The authenticated buyer's online-course learner surface: enrolled courses, lesson/course completion, the exam, and the completion certificate. Course content (paid lesson media, writeups, pins) is delivered only to enrolled ticket holders; media links returned here are short-lived signed /media URLs. Buyer auth (a ticket for the course) required.
type CoursesService struct{ c *Client }

// Mine List the buyer's enrolled courses, each with course meta and a progress summary (started courses first). No lesson content.
func (s *CoursesService) Mine(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/courses/mine", opts)
}

// Get Get one course's full learner payload: meta + progress + lessons (syllabus, with completed flags and signed media) or a unified content block.
func (s *CoursesService) Get(ctx context.Context, eventId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/courses/" + enc(eventId), opts)
}

// CompleteLesson Mark a syllabus lesson complete (idempotent, zero-based index). Completing the last requirement finishes the course and may issue a certificate.
func (s *CoursesService) CompleteLesson(ctx context.Context, eventId string, index string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/courses/" + enc(eventId) + "/lessons/" + enc(index) + "/complete", opts)
}

// UncompleteLesson Reverse a syllabus lesson completion (does not revoke an already-issued certificate).
func (s *CoursesService) UncompleteLesson(ctx context.Context, eventId string, index string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "DELETE", "/api/v1/courses/" + enc(eventId) + "/lessons/" + enc(index) + "/complete", opts)
}

// Complete Complete a unified course (unified courses only): marks the single learning unit complete.
func (s *CoursesService) Complete(ctx context.Context, eventId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/courses/" + enc(eventId) + "/complete", opts)
}

// Exam Get the course exam to take. Correct answers and explanations are stripped server-side.
func (s *CoursesService) Exam(ctx context.Context, eventId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/courses/" + enc(eventId) + "/exam", opts)
}

// SubmitExam Submit the exam (body: answers:[{questionId, selectedIndex}]) for server-side grading; a pass drives completion + certificate issuance.
func (s *CoursesService) SubmitExam(ctx context.Context, eventId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/courses/" + enc(eventId) + "/exam/submit", opts)
}

// Certificate Download the issued completion certificate as a PDF (404 CERTIFICATE_NOT_ISSUED until earned). Returns raw bytes and the content type.
func (s *CoursesService) Certificate(ctx context.Context, eventId string, opts ...RequestOption) ([]byte, string, error) {
	return s.c.doRaw(ctx, "GET", "/api/v1/courses/" + enc(eventId) + "/certificate", opts)
}

// IntegrationsService API keys: Manage your organization's own API keys (organizer owner/admin auth).
type IntegrationsService struct{ c *Client }

// CreateApiKey Create an API key (plaintext secret returned exactly once).
func (s *IntegrationsService) CreateApiKey(ctx context.Context, orgId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/organizer/integrations/org/" + enc(orgId) + "/api-keys", opts)
}

// ListApiKeys List API keys (prefixes and metadata only, never the secret).
func (s *IntegrationsService) ListApiKeys(ctx context.Context, orgId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/organizer/integrations/org/" + enc(orgId) + "/api-keys", opts)
}

// UpdateApiKey Update a key (rename, pause, re-scope).
func (s *IntegrationsService) UpdateApiKey(ctx context.Context, orgId string, keyId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "PUT", "/api/v1/organizer/integrations/org/" + enc(orgId) + "/api-keys/" + enc(keyId), opts)
}

// RotateApiKey Rotate a key's secret (new secret returned once; old one invalidated).
func (s *IntegrationsService) RotateApiKey(ctx context.Context, orgId string, keyId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/organizer/integrations/org/" + enc(orgId) + "/api-keys/" + enc(keyId) + "/rotate", opts)
}

// DeleteApiKey Revoke an API key.
func (s *IntegrationsService) DeleteApiKey(ctx context.Context, orgId string, keyId string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "DELETE", "/api/v1/organizer/integrations/org/" + enc(orgId) + "/api-keys/" + enc(keyId), opts)
}

// WebhooksService Webhooks: Register webhook endpoints, manage secrets, inspect and replay deliveries. (Use webhooks.verify() to validate inbound signatures.)
type WebhooksService struct{ c *Client }

// Create Create a webhook endpoint (signing secret returned exactly once).
func (s *WebhooksService) Create(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/webhooks", opts)
}

// List List webhook endpoints.
func (s *WebhooksService) List(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/webhooks", opts)
}

// Update Update a webhook endpoint.
func (s *WebhooksService) Update(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "PUT", "/api/v1/webhooks/" + enc(id), opts)
}

// Delete Delete a webhook endpoint.
func (s *WebhooksService) Delete(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "DELETE", "/api/v1/webhooks/" + enc(id), opts)
}

// Test Send a signed test event to the endpoint.
func (s *WebhooksService) Test(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/webhooks/" + enc(id) + "/test", opts)
}

// RotateSecret Rotate the signing secret (new secret returned once).
func (s *WebhooksService) RotateSecret(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/webhooks/" + enc(id) + "/rotate-secret", opts)
}

// Deliveries List delivery attempts for an endpoint.
func (s *WebhooksService) Deliveries(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/webhooks/" + enc(id) + "/deliveries", opts)
}

// Replay Replay a past delivery.
func (s *WebhooksService) Replay(ctx context.Context, id string, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "POST", "/api/v1/webhooks/deliveries/" + enc(id) + "/replay", opts)
}

// Catalog List every subscribable event type (no auth).
func (s *WebhooksService) Catalog(ctx context.Context, opts ...RequestOption) (json.RawMessage, error) {
	return s.c.do(ctx, "GET", "/api/v1/webhooks/catalog", opts)
}

