<?php

// AUTO-GENERATED by scripts/generate.mjs from spec/endpoints.json DO NOT EDIT.
// Regenerate with: node scripts/generate.mjs

namespace Zatabox\Resources;

use Zatabox\Client;

/**
 * Auth Account registration, password + passwordless sign-in, 2FA login and token refresh.
 */
class AuthResource
{
    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** Register an account; returns the user plus an accessToken/refreshToken pair. */
    public function register($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/auth/register", $opts + ['body' => $body]);
    }

    /** Log in with email + password; returns a JWT pair (or a 2FA challenge). */
    public function login($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/auth/login", $opts + ['body' => $body]);
    }

    /** Complete a 2FA login challenge; returns the JWT pair. */
    public function loginVerify2fa($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/auth/2fa-verify", $opts + ['body' => $body]);
    }

    /** Passwordless: email a buyer a 6-digit login code. */
    public function requestToken($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/auth/token/request", $opts + ['body' => $body]);
    }

    /** Passwordless: exchange email + 6-digit code for a JWT pair. */
    public function exchangeToken($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/auth/token/exchange", $opts + ['body' => $body]);
    }

    /** Refresh an expired access token (rotates the refresh token). */
    public function refresh($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/auth/refresh", $opts + ['body' => $body]);
    }

    /** Revoke a refresh token. */
    public function logout($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/auth/logout", $opts + ['body' => $body]);
    }
}

/**
 * Events (Public) Public event discovery and read, plus external ticket issuance.
 */
class EventsResource
{
    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** List and search published public events (cursor-paginated). Filters: q, category, city, and the read-only facets productType (event|reservation|digital) and course=true (courses within digital). */
    public function list($query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/events", $opts + ['query' => $query]);
    }

    /** Full-text + faceted event search. Same q/category/city/productType/course facets as events.list, plus date_from/date_to; each result carries category + read-only productType. */
    public function search($query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/search", $opts + ['query' => $query]);
    }

    /** Event detail by slug (organizer info, schedule, active ticket types; carries category + read-only productType). */
    public function get($slug, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/events/" . Client::enc($slug), $opts + ['query' => $query]);
    }

    /** List an event's ticket types with live availability. */
    public function tickets($id, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/events/" . Client::enc($id) . "/tickets", $opts + ['query' => $query]);
    }

    /** Issue tickets you sold elsewhere (developer-handled payment; 3% wallet fee on paid tickets). */
    public function issue($eventId, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/events/" . Client::enc($eventId) . "/issue", $opts + ['body' => $body]);
    }
}

/**
 * Seating (Public) Interactive venue seating: the buyer-facing seat map, live availability and temporary seat holds. Only events an organizer has attached a venue map to expose these (others 404 NO_SEATING). Buy seats by passing venueSeatIds on orders.create. No auth required.
 */
class SeatingResource
{
    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** Get the seat map: sections, seats with x/y coordinates, stage/label elements, and the ticket type + price per section. */
    public function seatmap($eventId, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/public/events/" . Client::enc($eventId) . "/seatmap", $opts + ['query' => $query]);
    }

    /** Live seat availability snapshot { sold, blocked, held } any seat id not listed is available. */
    public function seats($eventId, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/public/events/" . Client::enc($eventId) . "/seats", $opts + ['query' => $query]);
    }

    /** Server-Sent Events stream of live seat availability (a snapshot on connect, then seat_update events). (SSE returns the stream URL). */
    public function liveUrl($eventId, $query = null)
    {
        return $this->client->url("/api/v1/public/events/" . Client::enc($eventId) . "/seats/live", $query);
    }

    /** Hold (replace) the seats a buyer is selecting for an opaque holder token; returns { held, failed }. */
    public function hold($eventId, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/public/events/" . Client::enc($eventId) . "/seats/hold", $opts + ['body' => $body]);
    }

    /** Release a holder's seat holds (omit seatIds in the body to release all of them). */
    public function releaseHold($eventId, $body = null, array $opts = [])
    {
        return $this->client->request('DELETE', "/api/v1/public/events/" . Client::enc($eventId) . "/seats/hold", $opts + ['body' => $body]);
    }
}

/**
 * Organizer Organizer surface: organization read, events, ticket types, schedule sessions, seating sections and promo codes.
 */
class OrganizerResource
{
    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** Get organization details and per-currency wallet balances. */
    public function getOrganization($id, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/organizer/organizations/" . Client::enc($id), $opts + ['query' => $query]);
    }

    /** Create a draft event. */
    public function createEvent($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/organizer/events", $opts + ['body' => $body]);
    }

    /** Partial-update an event. */
    public function updateEvent($id, $body = null, array $opts = [])
    {
        return $this->client->request('PUT', "/api/v1/organizer/events/" . Client::enc($id), $opts + ['body' => $body]);
    }

    /** Publish a draft event. */
    public function publishEvent($id, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/organizer/events/" . Client::enc($id) . "/publish", $opts + ['body' => $body]);
    }

    /** Unpublish a published event back to draft. */
    public function unpublishEvent($id, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/organizer/events/" . Client::enc($id) . "/unpublish", $opts + ['body' => $body]);
    }

    /** Cancel an event. */
    public function deleteEvent($id, $body = null, array $opts = [])
    {
        return $this->client->request('DELETE', "/api/v1/organizer/events/" . Client::enc($id), $opts + ['body' => $body]);
    }

    /** Create a ticket type. */
    public function createTicket($id, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/organizer/events/" . Client::enc($id) . "/tickets", $opts + ['body' => $body]);
    }

    /** List schedule sessions (running order). */
    public function schedule($id, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/organizer/events/" . Client::enc($id) . "/schedule", $opts + ['query' => $query]);
    }

    /** Add a schedule session. */
    public function createSchedule($id, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/organizer/events/" . Client::enc($id) . "/schedule", $opts + ['body' => $body]);
    }

    /** Update a schedule session. */
    public function updateSchedule($id, $sessionId, $body = null, array $opts = [])
    {
        return $this->client->request('PUT', "/api/v1/organizer/events/" . Client::enc($id) . "/schedule/" . Client::enc($sessionId), $opts + ['body' => $body]);
    }

    /** Delete a schedule session. */
    public function deleteSchedule($id, $sessionId, $body = null, array $opts = [])
    {
        return $this->client->request('DELETE', "/api/v1/organizer/events/" . Client::enc($id) . "/schedule/" . Client::enc($sessionId), $opts + ['body' => $body]);
    }

    /** List seating/capacity sections. */
    public function sections($id, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/organizer/events/" . Client::enc($id) . "/sections", $opts + ['query' => $query]);
    }

    /** Add a seating section. */
    public function createSection($id, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/organizer/events/" . Client::enc($id) . "/sections", $opts + ['body' => $body]);
    }

    /** Update a seating section. */
    public function updateSection($id, $sectionId, $body = null, array $opts = [])
    {
        return $this->client->request('PUT', "/api/v1/organizer/events/" . Client::enc($id) . "/sections/" . Client::enc($sectionId), $opts + ['body' => $body]);
    }

    /** Delete a seating section. */
    public function deleteSection($id, $sectionId, $body = null, array $opts = [])
    {
        return $this->client->request('DELETE', "/api/v1/organizer/events/" . Client::enc($id) . "/sections/" . Client::enc($sectionId), $opts + ['body' => $body]);
    }

    /** Browse published venue seat maps you can attach to an event (interactive seating). */
    public function venues($query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/organizer/venues", $opts + ['query' => $query]);
    }

    /** Get an event's interactive-seating setup: attached map, section→ticket-type pricing, and blocked/sold seats. */
    public function getEventSeating($id, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/organizer/events/" . Client::enc($id) . "/seating", $opts + ['query' => $query]);
    }

    /** Attach a published venue map to the event (body: venueMapId, optional mode/holdTtlSeconds). */
    public function attachSeating($id, $body = null, array $opts = [])
    {
        return $this->client->request('PUT', "/api/v1/organizer/events/" . Client::enc($id) . "/seating", $opts + ['body' => $body]);
    }

    /** Remove interactive seating from the event (only before any seat sells). */
    public function detachSeating($id, $body = null, array $opts = [])
    {
        return $this->client->request('DELETE', "/api/v1/organizer/events/" . Client::enc($id) . "/seating", $opts + ['body' => $body]);
    }

    /** Map each venue section to one of the event's ticket types (body: mappings:[{venueSectionId, ticketTypeId}]). */
    public function setSeatingPricing($id, $body = null, array $opts = [])
    {
        return $this->client->request('PUT', "/api/v1/organizer/events/" . Client::enc($id) . "/seating/pricing", $opts + ['body' => $body]);
    }

    /** Block or unblock seats for the event (body: block:[seatId], unblock:[seatId]). */
    public function setSeatingBlocks($id, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/organizer/events/" . Client::enc($id) . "/seating/blocks", $opts + ['body' => $body]);
    }

    /** List promo codes (optionally filtered by event). */
    public function promoCodes($query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/organizer/promo-codes", $opts + ['query' => $query]);
    }

    /** Create a promo code. */
    public function createPromoCode($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/organizer/promo-codes", $opts + ['body' => $body]);
    }

    /** Update a promo code. */
    public function updatePromoCode($id, $body = null, array $opts = [])
    {
        return $this->client->request('PUT', "/api/v1/organizer/promo-codes/" . Client::enc($id), $opts + ['body' => $body]);
    }

    /** Delete or disable a promo code. */
    public function deletePromoCode($id, $body = null, array $opts = [])
    {
        return $this->client->request('DELETE', "/api/v1/organizer/promo-codes/" . Client::enc($id), $opts + ['body' => $body]);
    }
}

/**
 * Event page customization Per-event public-page theming and the “Good to know” FAQ.
 */
class EventCustomizationResource
{
    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** Get an event's page customization (theme, layout, FAQ, SEO). */
    public function get($id, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/organizer/event-customization/" . Client::enc($id), $opts + ['query' => $query]);
    }

    /** Update an event's page customization (incl. the FAQ list). */
    public function update($id, $body = null, array $opts = [])
    {
        return $this->client->request('PUT', "/api/v1/organizer/event-customization/" . Client::enc($id), $opts + ['body' => $body]);
    }
}

/**
 * Tickets Checkout-time ticket helpers.
 */
class TicketsResource
{
    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** Validate a promo code against a cart (read-only preview, does not consume a use). */
    public function validatePromo($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/tickets/promo/validate", $opts + ['body' => $body]);
    }
}

/**
 * Orders Carted checkout: create, read, pay, cancel.
 */
class OrdersResource
{
    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** Create an order (guest checkout needs only name + email). */
    public function create($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/orders", $opts + ['body' => $body]);
    }

    /** Get an order (pass ?token for guest reads). */
    public function get($id, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/orders/" . Client::enc($id), $opts + ['query' => $query]);
    }

    /** Initiate payment (provider: nowpayments | paystack | flutterwave). */
    public function pay($id, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/orders/" . Client::enc($id) . "/pay", $opts + ['body' => $body]);
    }

    /** Cancel an unpaid order and release held inventory. */
    public function cancel($id, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/orders/" . Client::enc($id) . "/cancel", $opts + ['body' => $body]);
    }
}

/**
 * Payments Verify charges, read payment status, list crypto coins.
 */
class PaymentsResource
{
    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** Actively verify a payment with the provider and issue tickets (idempotent, poll-safe). */
    public function verify($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/payments/verify", $opts + ['body' => $body]);
    }

    /** Read payment/order status and attempts (read-only). */
    public function get($orderId, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/payments/" . Client::enc($orderId), $opts + ['query' => $query]);
    }

    /** List supported NOWPayments crypto coins (for the payCurrency value). */
    public function cryptoCurrencies($query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/payments/crypto/currencies", $opts + ['query' => $query]);
    }
}

/**
 * Check-in Gate scanning, offline manifests + sync, live stats.
 */
class CheckinResource
{
    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** Validate a QR, barcode or 6-character door code at the gate. */
    public function scan($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/checkin/scan", $opts + ['body' => $body]);
    }

    /** Manually check in a typed ticket code. */
    public function manual($id, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/checkin/event/" . Client::enc($id) . "/manual", $opts + ['body' => $body]);
    }

    /** Hashed guest-list manifest for offline scanning (pass ?since for a delta). */
    public function manifest($id, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/checkin/event/" . Client::enc($id) . "/manifest", $opts + ['query' => $query]);
    }

    /** Sync up to 500 queued offline scans. */
    public function batch($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/checkin/batch", $opts + ['body' => $body]);
    }

    /** Check-in totals, capacity %, entry rate and per-gate breakdown. */
    public function stats($id, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/checkin/event/" . Client::enc($id) . "/stats", $opts + ['query' => $query]);
    }

    /** Per-gate check-in stats slice. */
    public function gate($id, $gate, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/checkin/event/" . Client::enc($id) . "/gate/" . Client::enc($gate), $opts + ['query' => $query]);
    }

    /** Server-Sent Events stream a stats snapshot every 2 seconds. (SSE returns the stream URL). */
    public function liveUrl($id, $query = null)
    {
        return $this->client->url("/api/v1/checkin/event/" . Client::enc($id) . "/live", $query);
    }
}

/**
 * Community Verified-attendee reviews, organizer follows/subscribers and event waitlists.
 */
class CommunityResource
{
    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** Review an event (checked-in ticket holders only; ticketCode + email prove attendance). */
    public function submitReview($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/community/reviews", $opts + ['body' => $body]);
    }

    /** Follow an organizer (subscribe to new-event announcements). */
    public function follow($orgId, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/community/orgs/" . Client::enc($orgId) . "/follow", $opts + ['body' => $body]);
    }

    /** List an organizer's subscribers (organizer auth). */
    public function followers($orgId, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/community/orgs/" . Client::enc($orgId) . "/followers", $opts + ['query' => $query]);
    }

    /** Remove a subscriber (organizer auth). */
    public function removeFollower($orgId, $followerId, $body = null, array $opts = [])
    {
        return $this->client->request('DELETE', "/api/v1/community/orgs/" . Client::enc($orgId) . "/followers/" . Client::enc($followerId), $opts + ['body' => $body]);
    }

    /** Join an event waitlist (offers fire on cancellations). */
    public function joinWaitlist($eventId, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/community/events/" . Client::enc($eventId) . "/waitlist", $opts + ['body' => $body]);
    }
}

/**
 * Growth (Organizer) Comp tickets, CSV import, broadcasts and attendee tags.
 */
class GrowthResource
{
    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** Bulk-mint and email complimentary tickets. */
    public function mintComps($eventId, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/organizer/growth/events/" . Client::enc($eventId) . "/comps", $opts + ['body' => $body]);
    }

    /** Import attendees (comp tickets) from CSV. */
    public function importCompsCsv($eventId, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/organizer/growth/events/" . Client::enc($eventId) . "/comps/import-csv", $opts + ['body' => $body]);
    }

    /** Email a broadcast to an event's attendees (replies thread to the organizer inbox). */
    public function broadcastEvent($eventId, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/organizer/growth/events/" . Client::enc($eventId) . "/broadcast", $opts + ['body' => $body]);
    }

    /** Tag attendees (additive; powers broadcast filters and CRM segments). */
    public function addTags($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/organizer/growth/tags", $opts + ['body' => $body]);
    }

    /** Remove an attendee tag. */
    public function removeTag($body = null, array $opts = [])
    {
        return $this->client->request('DELETE', "/api/v1/organizer/growth/tags", $opts + ['body' => $body]);
    }
}

/**
 * Buyers The authenticated buyer: profile, ticket wallet, data export, refunds, reports and organizer messaging.
 */
class UsersResource
{
    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** Current buyer profile. */
    public function me($query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/users/me", $opts + ['query' => $query]);
    }

    /** The buyer's ticket wallet (cursor-paginated). */
    public function tickets($query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/users/me/tickets", $opts + ['query' => $query]);
    }

    /** GDPR data export one JSON download of everything on the account. */
    public function export($query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/users/me/export", $opts + ['query' => $query]);
    }

    /** Request a refund for a ticket. */
    public function createRefund($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/users/me/refunds", $opts + ['body' => $body]);
    }

    /** File a report against an event or organizer. */
    public function createReport($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/users/me/reports", $opts + ['body' => $body]);
    }

    /** The buyer's message threads with organizers. */
    public function messages($query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/users/me/messages", $opts + ['query' => $query]);
    }

    /** Message the organizer about a ticket (rate-limited). */
    public function sendTicketMessage($ticketId, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/users/me/tickets/" . Client::enc($ticketId) . "/message", $opts + ['body' => $body]);
    }
}

/**
 * Courses (Learner) The authenticated buyer's online-course learner surface: enrolled courses, lesson/course completion, the exam, and the completion certificate. Course content (paid lesson media, writeups, pins) is delivered only to enrolled ticket holders; media links returned here are short-lived signed /media URLs. Buyer auth (a ticket for the course) required.
 */
class CoursesResource
{
    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** List the buyer's enrolled courses, each with course meta and a progress summary (started courses first). No lesson content. */
    public function mine($query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/courses/mine", $opts + ['query' => $query]);
    }

    /** Get one course's full learner payload: meta + progress + lessons (syllabus, with completed flags and signed media) or a unified content block. */
    public function get($eventId, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/courses/" . Client::enc($eventId), $opts + ['query' => $query]);
    }

    /** Mark a syllabus lesson complete (idempotent, zero-based index). Completing the last requirement finishes the course and may issue a certificate. */
    public function completeLesson($eventId, $index, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/courses/" . Client::enc($eventId) . "/lessons/" . Client::enc($index) . "/complete", $opts + ['body' => $body]);
    }

    /** Reverse a syllabus lesson completion (does not revoke an already-issued certificate). */
    public function uncompleteLesson($eventId, $index, $body = null, array $opts = [])
    {
        return $this->client->request('DELETE', "/api/v1/courses/" . Client::enc($eventId) . "/lessons/" . Client::enc($index) . "/complete", $opts + ['body' => $body]);
    }

    /** Complete a unified course (unified courses only): marks the single learning unit complete. */
    public function complete($eventId, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/courses/" . Client::enc($eventId) . "/complete", $opts + ['body' => $body]);
    }

    /** Get the course exam to take. Correct answers and explanations are stripped server-side. */
    public function exam($eventId, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/courses/" . Client::enc($eventId) . "/exam", $opts + ['query' => $query]);
    }

    /** Submit the exam (body: answers:[{questionId, selectedIndex}]) for server-side grading; a pass drives completion + certificate issuance. */
    public function submitExam($eventId, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/courses/" . Client::enc($eventId) . "/exam/submit", $opts + ['body' => $body]);
    }

    /** Download the issued completion certificate as a PDF (404 CERTIFICATE_NOT_ISSUED until earned). */
    public function certificate($eventId, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/courses/" . Client::enc($eventId) . "/certificate", $opts + ['query' => $query, 'raw' => true]);
    }
}

/**
 * API keys Manage your organization's own API keys (organizer owner/admin auth).
 */
class IntegrationsResource
{
    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** Create an API key (plaintext secret returned exactly once). */
    public function createApiKey($orgId, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/organizer/integrations/org/" . Client::enc($orgId) . "/api-keys", $opts + ['body' => $body]);
    }

    /** List API keys (prefixes and metadata only, never the secret). */
    public function listApiKeys($orgId, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/organizer/integrations/org/" . Client::enc($orgId) . "/api-keys", $opts + ['query' => $query]);
    }

    /** Update a key (rename, pause, re-scope). */
    public function updateApiKey($orgId, $keyId, $body = null, array $opts = [])
    {
        return $this->client->request('PUT', "/api/v1/organizer/integrations/org/" . Client::enc($orgId) . "/api-keys/" . Client::enc($keyId), $opts + ['body' => $body]);
    }

    /** Rotate a key's secret (new secret returned once; old one invalidated). */
    public function rotateApiKey($orgId, $keyId, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/organizer/integrations/org/" . Client::enc($orgId) . "/api-keys/" . Client::enc($keyId) . "/rotate", $opts + ['body' => $body]);
    }

    /** Revoke an API key. */
    public function deleteApiKey($orgId, $keyId, $body = null, array $opts = [])
    {
        return $this->client->request('DELETE', "/api/v1/organizer/integrations/org/" . Client::enc($orgId) . "/api-keys/" . Client::enc($keyId), $opts + ['body' => $body]);
    }
}

/**
 * Webhooks Register webhook endpoints, manage secrets, inspect and replay deliveries. (Use webhooks.verify() to validate inbound signatures.)
 */
class WebhooksResource
{
    /** @var Client */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /** Create a webhook endpoint (signing secret returned exactly once). */
    public function create($body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/webhooks", $opts + ['body' => $body]);
    }

    /** List webhook endpoints. */
    public function list($query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/webhooks", $opts + ['query' => $query]);
    }

    /** Update a webhook endpoint. */
    public function update($id, $body = null, array $opts = [])
    {
        return $this->client->request('PUT', "/api/v1/webhooks/" . Client::enc($id), $opts + ['body' => $body]);
    }

    /** Delete a webhook endpoint. */
    public function delete($id, $body = null, array $opts = [])
    {
        return $this->client->request('DELETE', "/api/v1/webhooks/" . Client::enc($id), $opts + ['body' => $body]);
    }

    /** Send a signed test event to the endpoint. */
    public function test($id, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/webhooks/" . Client::enc($id) . "/test", $opts + ['body' => $body]);
    }

    /** Rotate the signing secret (new secret returned once). */
    public function rotateSecret($id, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/webhooks/" . Client::enc($id) . "/rotate-secret", $opts + ['body' => $body]);
    }

    /** List delivery attempts for an endpoint. */
    public function deliveries($id, $query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/webhooks/" . Client::enc($id) . "/deliveries", $opts + ['query' => $query]);
    }

    /** Replay a past delivery. */
    public function replay($id, $body = null, array $opts = [])
    {
        return $this->client->request('POST', "/api/v1/webhooks/deliveries/" . Client::enc($id) . "/replay", $opts + ['body' => $body]);
    }

    /** List every subscribable event type (no auth). */
    public function catalog($query = null, array $opts = [])
    {
        return $this->client->request('GET', "/api/v1/webhooks/catalog", $opts + ['query' => $query]);
    }
}

/** Maps each namespace to its resource class. */
final class Registry
{
    const MAP = [
        'auth' => AuthResource::class,
        'events' => EventsResource::class,
        'seating' => SeatingResource::class,
        'organizer' => OrganizerResource::class,
        'eventCustomization' => EventCustomizationResource::class,
        'tickets' => TicketsResource::class,
        'orders' => OrdersResource::class,
        'payments' => PaymentsResource::class,
        'checkin' => CheckinResource::class,
        'community' => CommunityResource::class,
        'growth' => GrowthResource::class,
        'users' => UsersResource::class,
        'courses' => CoursesResource::class,
        'integrations' => IntegrationsResource::class,
        'webhooks' => WebhooksResource::class,
    ];
}

