#!/usr/bin/env node
// Zatabox SDK code generator.
//
// Reads spec/endpoints.json (the canonical manifest) and emits the *resource
// layer* for every SDK so the five languages never drift. The runtime core of
// each SDK is hand-written; only the thin per-endpoint method shims are
// generated here. Run from anywhere:  node scripts/generate.mjs
//
// Zero dependencies Node stdlib only.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const manifest = JSON.parse(readFileSync(join(ROOT, 'spec', 'endpoints.json'), 'utf8'));

// ── manifest validation (fail loudly before emitting anything) ──────────────
(function validate() {
  const seen = new Set();
  const errs = [];
  for (const g of manifest.groups) {
    const names = new Set();
    for (const e of g.endpoints) {
      if (e.kind === 'multipart') continue; // hand-written in each core
      if (names.has(e.name)) errs.push(`duplicate method ${g.ns}.${e.name}`);
      names.add(e.name);
      const key = `${e.method} ${e.path}`;
      if (seen.has(key)) errs.push(`duplicate route ${key}`);
      seen.add(key);
      if (!e.path.startsWith('/api/v1/')) errs.push(`bad path ${e.path}`);
      if (!/^(GET|POST|PUT|PATCH|DELETE)$/.test(e.method)) errs.push(`bad method ${e.method}`);
      if (!/^[a-z][a-zA-Z0-9]*$/.test(e.name)) errs.push(`bad name ${g.ns}.${e.name}`);
    }
  }
  if (errs.length) {
    console.error('manifest invalid:\n  ' + errs.join('\n  '));
    process.exit(1);
  }
})();

const WRITE_METHODS = new Set(['POST', 'PUT', 'PATCH', 'DELETE']);
const isWrite = (m) => WRITE_METHODS.has(m);

// ── name casing helpers ─────────────────────────────────────────────────────
const snake = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2').toLowerCase();
const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const camel = (s) => s.charAt(0).toLowerCase() + s.slice(1);

// ── path templating ─────────────────────────────────────────────────────────
// Returns { params: [...names], tokens: [{lit}|{param}] }
function parsePath(path) {
  const params = [];
  const tokens = [];
  const re = /:([a-zA-Z][a-zA-Z0-9]*)/g;
  let last = 0;
  let m;
  while ((m = re.exec(path))) {
    if (m.index > last) tokens.push({ lit: path.slice(last, m.index) });
    tokens.push({ param: m[1] });
    params.push(m[1]);
    last = m.index + m[0].length;
  }
  if (last < path.length) tokens.push({ lit: path.slice(last) });
  return { params, tokens };
}

// Build a path expression string given an encoder template and an identifier
// mapper for params. concat joins with " + ".
function pathExpr(tokens, enc, ident, q = '"', sep = ' + ') {
  if (tokens.length === 1 && tokens[0].lit !== undefined) return `${q}${tokens[0].lit}${q}`;
  return tokens
    .map((t) => (t.lit !== undefined ? `${q}${t.lit}${q}` : enc(ident(t.param))))
    .join(sep);
}

const banner = (cmt) =>
  `${cmt} AUTO-GENERATED by scripts/generate.mjs from spec/endpoints.json DO NOT EDIT.\n${cmt} Regenerate with: node scripts/generate.mjs\n`;

function out(rel, content) {
  const full = join(ROOT, rel);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content);
  console.log('  wrote', rel, `(${content.split('\n').length} lines)`);
}

// ════════════════════════════════════════════════════════════════════════════
// Node.js
// ════════════════════════════════════════════════════════════════════════════
function genNode() {
  const L = [];
  L.push("'use strict';");
  L.push(banner('//'));
  L.push('const enc = (v) => encodeURIComponent(String(v));');
  L.push('');
  L.push('// Attaches every resource namespace to a ZataboxClient instance.');
  L.push('function attachResources(client) {');
  for (const g of manifest.groups) {
    L.push(`  // ${g.title} ${g.desc}`);
    L.push(`  client.${camel(g.ns)} = {`);
    for (const e of g.endpoints) {
      if (e.kind === 'multipart') continue; // hand-written in each core
      const { params, tokens } = parsePath(e.path);
      const ident = (p) => camel(p);
      const pe = pathExpr(tokens, (id) => `enc(${id})`, ident);
      const args = params.map(ident);
      if (e.kind === 'sse') {
        const sig = [...args, 'query'].join(', ');
        L.push(`    // ${e.desc} (SSE returns the stream URL)`);
        L.push(`    ${e.name}Url: (${sig}) => client._url(${pe}, query),`);
        continue;
      }
      const payload = isWrite(e.method) ? 'body' : 'query';
      const sig = [...args, payload, 'opts'].join(', ');
      const optBag = [`${payload}`, e.kind === 'binary' ? 'raw: true' : null, '...(opts || {})']
        .filter(Boolean)
        .join(', ');
      L.push(`    // ${e.desc}`);
      L.push(`    ${e.name}: (${sig}) => client.request('${e.method}', ${pe}, { ${optBag} }),`);
    }
    L.push('  };');
  }
  L.push('}');
  L.push('');
  L.push('module.exports = { attachResources };');
  out('node/src/resources.generated.js', L.join('\n') + '\n');
  genNodeTypes();
}

// TypeScript declarations for the generated namespaces.
function genNodeTypes() {
  const T = [];
  const hasBinary = manifest.groups.some((g) => g.endpoints.some((e) => e.kind === 'binary'));
  T.push(banner('//'));
  T.push(
    hasBinary
      ? "import type { RequestOptions, BinaryResponse } from './index';"
      : "import type { RequestOptions } from './index';"
  );
  T.push('');
  const ifaces = [];
  for (const g of manifest.groups) {
    const iface = pascal(g.ns) + 'Namespace';
    ifaces.push([camel(g.ns), iface]);
    T.push(`/** ${g.title} ${g.desc} */`);
    T.push(`export interface ${iface} {`);
    for (const e of g.endpoints) {
      if (e.kind === 'multipart') continue; // hand-written in each core
      const { params } = parsePath(e.path);
      const pargs = params.map((p) => `${camel(p)}: string`);
      if (e.kind === 'sse') {
        T.push(`  /** ${e.desc} (SSE returns the stream URL) */`);
        T.push(`  ${e.name}Url(${[...pargs, 'query?: Record<string, any>'].join(', ')}): string;`);
        continue;
      }
      const payload = isWrite(e.method)
        ? 'body?: any'
        : 'query?: Record<string, any>';
      const ret = e.kind === 'binary' ? 'Promise<BinaryResponse>' : 'Promise<any>';
      T.push(`  /** ${e.desc} */`);
      T.push(`  ${e.name}(${[...pargs, payload, 'opts?: RequestOptions'].join(', ')}): ${ret};`);
    }
    T.push('}');
    T.push('');
  }
  T.push('/** All resource namespaces attached to a ZataboxClient. */');
  T.push('export interface ResourceNamespaces {');
  for (const [prop, iface] of ifaces) T.push(`  ${prop}: ${iface};`);
  T.push('}');
  out('node/src/resources.generated.d.ts', T.join('\n') + '\n');
}

// ════════════════════════════════════════════════════════════════════════════
// Python
// ════════════════════════════════════════════════════════════════════════════
function genPython() {
  const L = [];
  L.push(banner('#').trimEnd());
  L.push('from ._http import enc');
  L.push('');
  L.push('');
  for (const g of manifest.groups) {
    const cls = pascal(g.ns) + 'Resource';
    L.push(`class ${cls}:`);
    L.push(`    """${g.title} ${g.desc}"""`);
    L.push('');
    L.push('    def __init__(self, client):');
    L.push('        self._c = client');
    for (const e of g.endpoints) {
      if (e.kind === 'multipart') continue; // hand-written in each core
      const { params, tokens } = parsePath(e.path);
      const ident = (p) => snake(p);
      const pe = pathExpr(tokens, (id) => `enc(${id})`, ident);
      const args = params.map(ident);
      L.push('');
      if (e.kind === 'sse') {
        const sig = ['self', ...args, 'query=None'].join(', ');
        L.push(`    def ${snake(e.name)}_url(${sig}):`);
        L.push(`        """${e.desc} (SSE returns the stream URL)."""`);
        L.push(`        return self._c._url(${pe}, query)`);
        continue;
      }
      const payload = isWrite(e.method) ? 'body' : 'query';
      const sig = ['self', ...args, `${payload}=None`, '**opts'].join(', ');
      const call = [
        `"${e.method}"`,
        pe,
        `${payload}=${payload}`,
        e.kind === 'binary' ? 'raw=True' : null,
        '**opts',
      ]
        .filter(Boolean)
        .join(', ');
      L.push(`    def ${snake(e.name)}(${sig}):`);
      L.push(`        """${e.desc}"""`);
      L.push(`        return self._c._request(${call})`);
    }
    L.push('');
    L.push('');
  }
  // registry the client uses to attach namespaces
  L.push('RESOURCES = {');
  for (const g of manifest.groups) {
    L.push(`    "${snake(g.ns)}": ${pascal(g.ns)}Resource,`);
  }
  L.push('}');
  out('python/zatabox/resources.py', L.join('\n') + '\n');
}

// ════════════════════════════════════════════════════════════════════════════
// Ruby
// ════════════════════════════════════════════════════════════════════════════
function genRuby() {
  const L = [];
  L.push('# frozen_string_literal: true');
  L.push('');
  L.push(banner('#').trimEnd());
  L.push('module Zatabox');
  L.push('  module Resources');
  for (const g of manifest.groups) {
    const cls = pascal(g.ns);
    L.push(`    # ${g.title} ${g.desc}`);
    L.push(`    class ${cls}`);
    L.push('      def initialize(client)');
    L.push('        @client = client');
    L.push('      end');
    for (const e of g.endpoints) {
      if (e.kind === 'multipart') continue; // hand-written in each core
      const { params, tokens } = parsePath(e.path);
      const ident = (p) => snake(p);
      const pe = pathExpr(tokens, (id) => `enc(${id})`, ident);
      const args = params.map(ident);
      L.push('');
      if (e.kind === 'sse') {
        const sig = [...args, 'query = nil'].join(', ');
        L.push(`      # ${e.desc} (SSE returns the stream URL)`);
        L.push(`      def ${snake(e.name)}_url(${sig})`);
        L.push(`        @client.url(${pe}, query)`);
        L.push('      end');
        continue;
      }
      const payload = isWrite(e.method) ? 'body' : 'query';
      // A *positional* opts hash (not **opts) so a brace-less hash like
      // `create(items: [])` binds to `body`, not the options bag (Ruby 2.6+).
      const sig = [...args, `${payload} = nil`, 'opts = {}'].join(', ');
      const call = [
        `"${e.method}"`,
        pe,
        `${payload}: ${payload}`,
        e.kind === 'binary' ? 'raw: true' : null,
        '**opts',
      ]
        .filter(Boolean)
        .join(', ');
      L.push(`      # ${e.desc}`);
      L.push(`      def ${snake(e.name)}(${sig})`);
      L.push(`        @client.request(${call})`);
      L.push('      end');
    }
    L.push('');
    L.push('      private');
    L.push('');
    L.push('      def enc(value)');
    L.push('        Zatabox.encode(value)');
    L.push('      end');
    L.push('    end');
    L.push('');
  }
  L.push('    # ns symbol => resource class');
  L.push('    REGISTRY = {');
  for (const g of manifest.groups) {
    L.push(`      ${snake(g.ns)}: ${pascal(g.ns)},`);
  }
  L.push('    }.freeze');
  L.push('  end');
  L.push('end');
  out('ruby/lib/zatabox/resources.rb', L.join('\n') + '\n');
}

// ════════════════════════════════════════════════════════════════════════════
// PHP
// ════════════════════════════════════════════════════════════════════════════
function genPhp() {
  const L = [];
  L.push('<?php');
  L.push('');
  L.push(banner('//').trimEnd());
  L.push('');
  L.push('namespace Zatabox\\Resources;');
  L.push('');
  L.push('use Zatabox\\Client;');
  L.push('');
  for (const g of manifest.groups) {
    const cls = pascal(g.ns) + 'Resource';
    L.push('/**');
    L.push(` * ${g.title} ${g.desc}`);
    L.push(' */');
    L.push(`class ${cls}`);
    L.push('{');
    L.push('    /** @var Client */');
    L.push('    private $client;');
    L.push('');
    L.push('    public function __construct(Client $client)');
    L.push('    {');
    L.push('        $this->client = $client;');
    L.push('    }');
    for (const e of g.endpoints) {
      if (e.kind === 'multipart') continue; // hand-written in each core
      const { params, tokens } = parsePath(e.path);
      const ident = (p) => '$' + camel(p);
      const pe = pathExpr(tokens, (id) => `Client::enc(${id})`, ident, '"', ' . ');
      const args = params.map(ident);
      L.push('');
      if (e.kind === 'sse') {
        const sig = [...args, '$query = null'].join(', ');
        L.push(`    /** ${e.desc} (SSE returns the stream URL). */`);
        L.push(`    public function ${camel(e.name)}Url(${sig})`);
        L.push('    {');
        L.push(`        return $this->client->url(${pe}, $query);`);
        L.push('    }');
        continue;
      }
      const payload = isWrite(e.method) ? '$body' : '$query';
      const sig = [...args, `${payload} = null`, 'array $opts = []'].join(', ');
      const optsParts = [`'${isWrite(e.method) ? 'body' : 'query'}' => ${payload}`];
      if (e.kind === 'binary') optsParts.push("'raw' => true");
      L.push(`    /** ${e.desc} */`);
      L.push(`    public function ${camel(e.name)}(${sig})`);
      L.push('    {');
      L.push(`        return $this->client->request('${e.method}', ${pe}, $opts + [${optsParts.join(', ')}]);`);
      L.push('    }');
    }
    L.push('}');
    L.push('');
  }
  // Registry: camelCase namespace => resource class, consumed by the Client.
  L.push('/** Maps each namespace to its resource class. */');
  L.push('final class Registry');
  L.push('{');
  L.push('    const MAP = [');
  for (const g of manifest.groups) {
    L.push(`        '${camel(g.ns)}' => ${pascal(g.ns)}Resource::class,`);
  }
  L.push('    ];');
  L.push('}');
  L.push('');
  out('php/src/Resources.php', L.join('\n') + '\n');
}

// ════════════════════════════════════════════════════════════════════════════
// Go
// ════════════════════════════════════════════════════════════════════════════
function genGo() {
  const L = [];
  L.push(banner('//').trimEnd());
  L.push('');
  L.push('package zatabox');
  L.push('');
  L.push('import (');
  L.push('\t"context"');
  L.push('\t"encoding/json"');
  L.push(')');
  L.push('');
  // service struct fields on Client
  L.push('// services bundles every resource namespace; embedded in Client.');
  L.push('type services struct {');
  for (const g of manifest.groups) {
    L.push(`\t${pascal(g.ns)} *${pascal(g.ns)}Service`);
  }
  L.push('}');
  L.push('');
  L.push('func (c *Client) initServices() {');
  for (const g of manifest.groups) {
    L.push(`\tc.${pascal(g.ns)} = &${pascal(g.ns)}Service{c: c}`);
  }
  L.push('}');
  L.push('');
  for (const g of manifest.groups) {
    const svc = pascal(g.ns) + 'Service';
    L.push(`// ${svc} ${g.title}: ${g.desc}`);
    L.push(`type ${svc} struct{ c *Client }`);
    L.push('');
    for (const e of g.endpoints) {
      if (e.kind === 'multipart') continue; // hand-written in each core
      const { params, tokens } = parsePath(e.path);
      const ident = (p) => camel(p);
      const pe = pathExpr(tokens, (id) => `enc(${id})`, ident);
      const args = params.map((p) => `${camel(p)} string`);
      const name = pascal(e.name);
      if (e.kind === 'sse') {
        const sig = ['queryArgs ...map[string]interface{}'];
        L.push(`// ${name}URL ${e.desc} (SSE; returns the stream URL).`);
        L.push(`func (s *${svc}) ${name}URL(${[...args.map(a=>a), ...sig].join(', ')}) string {`);
        L.push(`\treturn s.c.url(${pe}, firstQuery(queryArgs))`);
        L.push('}');
        L.push('');
        continue;
      }
      if (e.kind === 'binary') {
        L.push(`// ${name} ${e.desc} Returns raw bytes and the content type.`);
        L.push(`func (s *${svc}) ${name}(ctx context.Context, ${[...args, 'opts ...RequestOption'].join(', ')}) ([]byte, string, error) {`);
        L.push(`\treturn s.c.doRaw(ctx, "${e.method}", ${pe}, opts)`);
        L.push('}');
        L.push('');
        continue;
      }
      L.push(`// ${name} ${e.desc}`);
      L.push(`func (s *${svc}) ${name}(ctx context.Context, ${[...args, 'opts ...RequestOption'].join(', ')}) (json.RawMessage, error) {`);
      L.push(`\treturn s.c.do(ctx, "${e.method}", ${pe}, opts)`);
      L.push('}');
      L.push('');
    }
  }
  out('go/resources_gen.go', L.join('\n') + '\n');
}

// ════════════════════════════════════════════════════════════════════════════
// README endpoint reference (injected between markers in each README)
// ════════════════════════════════════════════════════════════════════════════
const escPipe = (s) => String(s).replace(/\|/g, '\\|');

// Idiomatic method signature for a single endpoint, per language.
function refSig(lang, e) {
  const params = parsePath(e.path).params;
  const write = isWrite(e.method);
  const sse = e.kind === 'sse';
  const binary = e.kind === 'binary';
  if (lang === 'node') {
    const ps = params.map(camel);
    if (sse) return `${e.name}Url(${[...ps, 'query?'].join(', ')})`;
    const ret = binary ? ' → BinaryResponse' : '';
    return `${e.name}(${[...ps, write ? 'body?' : 'query?', 'opts?'].join(', ')})${ret}`;
  }
  if (lang === 'python') {
    const ps = params.map(snake);
    if (sse) return `${snake(e.name)}_url(${[...ps, 'query=None'].join(', ')})`;
    return `${snake(e.name)}(${[...ps, write ? 'body=None' : 'query=None', '**opts'].join(', ')})`;
  }
  if (lang === 'ruby') {
    const ps = params.map(snake);
    if (sse) return `${snake(e.name)}_url(${[...ps, 'query = nil'].join(', ')})`;
    return `${snake(e.name)}(${[...ps, write ? 'body = nil' : 'query = nil', 'opts = {}'].join(', ')})`;
  }
  if (lang === 'php') {
    const ps = params.map((p) => '$' + camel(p));
    if (sse) return `${camel(e.name)}Url(${[...ps, '$query = null'].join(', ')})`;
    return `${camel(e.name)}(${[...ps, write ? '$body = null' : '$query = null', 'array $opts = []'].join(', ')})`;
  }
  // go
  const ps = params.map(camel);
  if (sse) return `${pascal(e.name)}URL(${[...ps, 'query...'].join(', ')}) string`;
  if (binary) return `${pascal(e.name)}(ctx, ${[...ps, 'opts...'].join(', ')}) ([]byte, string, error)`;
  return `${pascal(e.name)}(ctx, ${[...ps, 'opts...'].join(', ')}) (json.RawMessage, error)`;
}

const NS_ACCESS = {
  node: (ns) => `client.${camel(ns)}`,
  python: (ns) => `client.${snake(ns)}`,
  ruby: (ns) => `client.${snake(ns)}`,
  php: (ns) => `$client->${camel(ns)}`,
  go: (ns) => `client.${pascal(ns)}`,
};

function buildReference(lang) {
  let count = 0;
  for (const g of manifest.groups) count += g.endpoints.length;
  const L = [];
  L.push(`The SDK exposes **${count} endpoints** across **${manifest.groups.length} namespaces**. Every method is listed below with its idiomatic signature, the underlying HTTP route, and what it does. Path parameters are positional; reads take an optional query map and writes take an optional body, both followed by a call-options bag.`);
  L.push('');
  for (const g of manifest.groups) {
    L.push(`### \`${NS_ACCESS[lang](g.ns)}\` ${g.title}`);
    L.push('');
    L.push(g.desc);
    L.push('');
    L.push('| Method | Endpoint | Description |');
    L.push('| --- | --- | --- |');
    for (const e of g.endpoints) {
      L.push(`| \`${escPipe(refSig(lang, e))}\` | \`${e.method} ${e.path}\` | ${escPipe(e.desc)} |`);
    }
    L.push('');
  }
  return L.join('\n');
}

const BEGIN = '<!-- BEGIN ENDPOINTS (generated by scripts/generate.mjs do not edit) -->';
const END = '<!-- END ENDPOINTS -->';

function injectReference(lang, relPath) {
  const full = join(ROOT, relPath);
  let src;
  try {
    src = readFileSync(full, 'utf8');
  } catch {
    console.warn(`  skip ${relPath} (not found)`);
    return;
  }
  const ref = buildReference(lang);
  const block = `${BEGIN}\n\n${ref}\n${END}`;
  const re = new RegExp(`${BEGIN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END}`);
  let next;
  if (re.test(src)) {
    next = src.replace(re, block);
  } else {
    console.warn(`  ${relPath}: no marker block appending`);
    next = src.replace(/\s*$/, '\n') + '\n' + block + '\n';
  }
  writeFileSync(full, next);
  console.log('  injected reference into', relPath);
}

function genReferences() {
  injectReference('node', 'node/README.md');
  injectReference('python', 'python/README.md');
  injectReference('ruby', 'ruby/README.md');
  injectReference('php', 'php/README.md');
  injectReference('go', 'go/README.md');
}

// ── run ─────────────────────────────────────────────────────────────────────
let count = 0;
for (const g of manifest.groups) count += g.endpoints.length;
console.log(`Zatabox SDK generator ${manifest.groups.length} namespaces, ${count} endpoints`);
console.log('Node:');    genNode();
console.log('Python:');  genPython();
console.log('Ruby:');    genRuby();
console.log('PHP:');     genPhp();
console.log('Go:');      genGo();
console.log('References:'); genReferences();
console.log('Done.');
