# frozen_string_literal: true

# AUTO-GENERATED by scripts/generate.mjs from spec/endpoints.json DO NOT EDIT.
# Regenerate with: node scripts/generate.mjs
module Zatabox
  module Resources
    # Auth Account registration, password + passwordless sign-in, 2FA login and token refresh.
    class Auth
      def initialize(client)
        @client = client
      end

      # Register an account; returns the user plus an accessToken/refreshToken pair.
      def register(body = nil, opts = {})
        @client.request("POST", "/api/v1/auth/register", body: body, **opts)
      end

      # Log in with email + password; returns a JWT pair (or a 2FA challenge).
      def login(body = nil, opts = {})
        @client.request("POST", "/api/v1/auth/login", body: body, **opts)
      end

      # Complete a 2FA login challenge; returns the JWT pair.
      def login_verify2fa(body = nil, opts = {})
        @client.request("POST", "/api/v1/auth/2fa-verify", body: body, **opts)
      end

      # Passwordless: email a buyer a 6-digit login code.
      def request_token(body = nil, opts = {})
        @client.request("POST", "/api/v1/auth/token/request", body: body, **opts)
      end

      # Passwordless: exchange email + 6-digit code for a JWT pair.
      def exchange_token(body = nil, opts = {})
        @client.request("POST", "/api/v1/auth/token/exchange", body: body, **opts)
      end

      # Refresh an expired access token (rotates the refresh token).
      def refresh(body = nil, opts = {})
        @client.request("POST", "/api/v1/auth/refresh", body: body, **opts)
      end

      # Revoke a refresh token.
      def logout(body = nil, opts = {})
        @client.request("POST", "/api/v1/auth/logout", body: body, **opts)
      end

      private

      def enc(value)
        Zatabox.encode(value)
      end
    end

    # Events (Public) Public event discovery and read, plus external ticket issuance.
    class Events
      def initialize(client)
        @client = client
      end

      # List and search published public events (cursor-paginated). Filters: q, category, city, and the read-only facets productType (event|reservation|digital) and course=true (courses within digital).
      def list(query = nil, opts = {})
        @client.request("GET", "/api/v1/events", query: query, **opts)
      end

      # Full-text + faceted event search. Same q/category/city/productType/course facets as events.list, plus date_from/date_to; each result carries category + read-only productType.
      def search(query = nil, opts = {})
        @client.request("GET", "/api/v1/search", query: query, **opts)
      end

      # Event detail by slug (organizer info, schedule, active ticket types; carries category + read-only productType).
      def get(slug, query = nil, opts = {})
        @client.request("GET", "/api/v1/events/" + enc(slug), query: query, **opts)
      end

      # List an event's ticket types with live availability.
      def tickets(id, query = nil, opts = {})
        @client.request("GET", "/api/v1/events/" + enc(id) + "/tickets", query: query, **opts)
      end

      # Issue tickets you sold elsewhere (developer-handled payment; 3% wallet fee on paid tickets).
      def issue(event_id, body = nil, opts = {})
        @client.request("POST", "/api/v1/events/" + enc(event_id) + "/issue", body: body, **opts)
      end

      private

      def enc(value)
        Zatabox.encode(value)
      end
    end

    # Seating (Public) Interactive venue seating: the buyer-facing seat map, live availability and temporary seat holds. Only events an organizer has attached a venue map to expose these (others 404 NO_SEATING). Buy seats by passing venueSeatIds on orders.create. No auth required.
    class Seating
      def initialize(client)
        @client = client
      end

      # Get the seat map: sections, seats with x/y coordinates, stage/label elements, and the ticket type + price per section.
      def seatmap(event_id, query = nil, opts = {})
        @client.request("GET", "/api/v1/public/events/" + enc(event_id) + "/seatmap", query: query, **opts)
      end

      # Live seat availability snapshot { sold, blocked, held } any seat id not listed is available.
      def seats(event_id, query = nil, opts = {})
        @client.request("GET", "/api/v1/public/events/" + enc(event_id) + "/seats", query: query, **opts)
      end

      # Server-Sent Events stream of live seat availability (a snapshot on connect, then seat_update events). (SSE returns the stream URL)
      def live_url(event_id, query = nil)
        @client.url("/api/v1/public/events/" + enc(event_id) + "/seats/live", query)
      end

      # Hold (replace) the seats a buyer is selecting for an opaque holder token; returns { held, failed }.
      def hold(event_id, body = nil, opts = {})
        @client.request("POST", "/api/v1/public/events/" + enc(event_id) + "/seats/hold", body: body, **opts)
      end

      # Release a holder's seat holds (omit seatIds in the body to release all of them).
      def release_hold(event_id, body = nil, opts = {})
        @client.request("DELETE", "/api/v1/public/events/" + enc(event_id) + "/seats/hold", body: body, **opts)
      end

      private

      def enc(value)
        Zatabox.encode(value)
      end
    end

    # Organizer Organizer surface: organization read, events, ticket types, schedule sessions, seating sections and promo codes.
    class Organizer
      def initialize(client)
        @client = client
      end

      # Get organization details and per-currency wallet balances.
      def get_organization(id, query = nil, opts = {})
        @client.request("GET", "/api/v1/organizer/organizations/" + enc(id), query: query, **opts)
      end

      # Create a draft event.
      def create_event(body = nil, opts = {})
        @client.request("POST", "/api/v1/organizer/events", body: body, **opts)
      end

      # Partial-update an event.
      def update_event(id, body = nil, opts = {})
        @client.request("PUT", "/api/v1/organizer/events/" + enc(id), body: body, **opts)
      end

      # Publish a draft event.
      def publish_event(id, body = nil, opts = {})
        @client.request("POST", "/api/v1/organizer/events/" + enc(id) + "/publish", body: body, **opts)
      end

      # Unpublish a published event back to draft.
      def unpublish_event(id, body = nil, opts = {})
        @client.request("POST", "/api/v1/organizer/events/" + enc(id) + "/unpublish", body: body, **opts)
      end

      # Cancel an event.
      def delete_event(id, body = nil, opts = {})
        @client.request("DELETE", "/api/v1/organizer/events/" + enc(id), body: body, **opts)
      end

      # Create a ticket type.
      def create_ticket(id, body = nil, opts = {})
        @client.request("POST", "/api/v1/organizer/events/" + enc(id) + "/tickets", body: body, **opts)
      end

      # List schedule sessions (running order).
      def schedule(id, query = nil, opts = {})
        @client.request("GET", "/api/v1/organizer/events/" + enc(id) + "/schedule", query: query, **opts)
      end

      # Add a schedule session.
      def create_schedule(id, body = nil, opts = {})
        @client.request("POST", "/api/v1/organizer/events/" + enc(id) + "/schedule", body: body, **opts)
      end

      # Update a schedule session.
      def update_schedule(id, session_id, body = nil, opts = {})
        @client.request("PUT", "/api/v1/organizer/events/" + enc(id) + "/schedule/" + enc(session_id), body: body, **opts)
      end

      # Delete a schedule session.
      def delete_schedule(id, session_id, body = nil, opts = {})
        @client.request("DELETE", "/api/v1/organizer/events/" + enc(id) + "/schedule/" + enc(session_id), body: body, **opts)
      end

      # List seating/capacity sections.
      def sections(id, query = nil, opts = {})
        @client.request("GET", "/api/v1/organizer/events/" + enc(id) + "/sections", query: query, **opts)
      end

      # Add a seating section.
      def create_section(id, body = nil, opts = {})
        @client.request("POST", "/api/v1/organizer/events/" + enc(id) + "/sections", body: body, **opts)
      end

      # Update a seating section.
      def update_section(id, section_id, body = nil, opts = {})
        @client.request("PUT", "/api/v1/organizer/events/" + enc(id) + "/sections/" + enc(section_id), body: body, **opts)
      end

      # Delete a seating section.
      def delete_section(id, section_id, body = nil, opts = {})
        @client.request("DELETE", "/api/v1/organizer/events/" + enc(id) + "/sections/" + enc(section_id), body: body, **opts)
      end

      # Browse published venue seat maps you can attach to an event (interactive seating).
      def venues(query = nil, opts = {})
        @client.request("GET", "/api/v1/organizer/venues", query: query, **opts)
      end

      # Get an event's interactive-seating setup: attached map, section→ticket-type pricing, and blocked/sold seats.
      def get_event_seating(id, query = nil, opts = {})
        @client.request("GET", "/api/v1/organizer/events/" + enc(id) + "/seating", query: query, **opts)
      end

      # Attach a published venue map to the event (body: venueMapId, optional mode/holdTtlSeconds).
      def attach_seating(id, body = nil, opts = {})
        @client.request("PUT", "/api/v1/organizer/events/" + enc(id) + "/seating", body: body, **opts)
      end

      # Remove interactive seating from the event (only before any seat sells).
      def detach_seating(id, body = nil, opts = {})
        @client.request("DELETE", "/api/v1/organizer/events/" + enc(id) + "/seating", body: body, **opts)
      end

      # Map each venue section to one of the event's ticket types (body: mappings:[{venueSectionId, ticketTypeId}]).
      def set_seating_pricing(id, body = nil, opts = {})
        @client.request("PUT", "/api/v1/organizer/events/" + enc(id) + "/seating/pricing", body: body, **opts)
      end

      # Block or unblock seats for the event (body: block:[seatId], unblock:[seatId]).
      def set_seating_blocks(id, body = nil, opts = {})
        @client.request("POST", "/api/v1/organizer/events/" + enc(id) + "/seating/blocks", body: body, **opts)
      end

      # List promo codes (optionally filtered by event).
      def promo_codes(query = nil, opts = {})
        @client.request("GET", "/api/v1/organizer/promo-codes", query: query, **opts)
      end

      # Create a promo code.
      def create_promo_code(body = nil, opts = {})
        @client.request("POST", "/api/v1/organizer/promo-codes", body: body, **opts)
      end

      # Update a promo code.
      def update_promo_code(id, body = nil, opts = {})
        @client.request("PUT", "/api/v1/organizer/promo-codes/" + enc(id), body: body, **opts)
      end

      # Delete or disable a promo code.
      def delete_promo_code(id, body = nil, opts = {})
        @client.request("DELETE", "/api/v1/organizer/promo-codes/" + enc(id), body: body, **opts)
      end

      private

      def enc(value)
        Zatabox.encode(value)
      end
    end

    # Event page customization Per-event public-page theming and the “Good to know” FAQ.
    class EventCustomization
      def initialize(client)
        @client = client
      end

      # Get an event's page customization (theme, layout, FAQ, SEO).
      def get(id, query = nil, opts = {})
        @client.request("GET", "/api/v1/organizer/event-customization/" + enc(id), query: query, **opts)
      end

      # Update an event's page customization (incl. the FAQ list).
      def update(id, body = nil, opts = {})
        @client.request("PUT", "/api/v1/organizer/event-customization/" + enc(id), body: body, **opts)
      end

      private

      def enc(value)
        Zatabox.encode(value)
      end
    end

    # Tickets Checkout-time ticket helpers.
    class Tickets
      def initialize(client)
        @client = client
      end

      # Validate a promo code against a cart (read-only preview, does not consume a use).
      def validate_promo(body = nil, opts = {})
        @client.request("POST", "/api/v1/tickets/promo/validate", body: body, **opts)
      end

      private

      def enc(value)
        Zatabox.encode(value)
      end
    end

    # Orders Carted checkout: create, read, pay, cancel.
    class Orders
      def initialize(client)
        @client = client
      end

      # Create an order (guest checkout needs only name + email).
      def create(body = nil, opts = {})
        @client.request("POST", "/api/v1/orders", body: body, **opts)
      end

      # Get an order (pass ?token for guest reads).
      def get(id, query = nil, opts = {})
        @client.request("GET", "/api/v1/orders/" + enc(id), query: query, **opts)
      end

      # Initiate payment (provider: nowpayments | paystack | flutterwave).
      def pay(id, body = nil, opts = {})
        @client.request("POST", "/api/v1/orders/" + enc(id) + "/pay", body: body, **opts)
      end

      # Cancel an unpaid order and release held inventory.
      def cancel(id, body = nil, opts = {})
        @client.request("POST", "/api/v1/orders/" + enc(id) + "/cancel", body: body, **opts)
      end

      private

      def enc(value)
        Zatabox.encode(value)
      end
    end

    # Payments Verify charges, read payment status, list crypto coins.
    class Payments
      def initialize(client)
        @client = client
      end

      # Actively verify a payment with the provider and issue tickets (idempotent, poll-safe).
      def verify(body = nil, opts = {})
        @client.request("POST", "/api/v1/payments/verify", body: body, **opts)
      end

      # Read payment/order status and attempts (read-only).
      def get(order_id, query = nil, opts = {})
        @client.request("GET", "/api/v1/payments/" + enc(order_id), query: query, **opts)
      end

      # List supported NOWPayments crypto coins (for the payCurrency value).
      def crypto_currencies(query = nil, opts = {})
        @client.request("GET", "/api/v1/payments/crypto/currencies", query: query, **opts)
      end

      private

      def enc(value)
        Zatabox.encode(value)
      end
    end

    # Check-in Gate scanning, offline manifests + sync, live stats.
    class Checkin
      def initialize(client)
        @client = client
      end

      # Validate a QR, barcode or 6-character door code at the gate.
      def scan(body = nil, opts = {})
        @client.request("POST", "/api/v1/checkin/scan", body: body, **opts)
      end

      # Manually check in a typed ticket code.
      def manual(id, body = nil, opts = {})
        @client.request("POST", "/api/v1/checkin/event/" + enc(id) + "/manual", body: body, **opts)
      end

      # Hashed guest-list manifest for offline scanning (pass ?since for a delta).
      def manifest(id, query = nil, opts = {})
        @client.request("GET", "/api/v1/checkin/event/" + enc(id) + "/manifest", query: query, **opts)
      end

      # Sync up to 500 queued offline scans.
      def batch(body = nil, opts = {})
        @client.request("POST", "/api/v1/checkin/batch", body: body, **opts)
      end

      # Check-in totals, capacity %, entry rate and per-gate breakdown.
      def stats(id, query = nil, opts = {})
        @client.request("GET", "/api/v1/checkin/event/" + enc(id) + "/stats", query: query, **opts)
      end

      # Per-gate check-in stats slice.
      def gate(id, gate, query = nil, opts = {})
        @client.request("GET", "/api/v1/checkin/event/" + enc(id) + "/gate/" + enc(gate), query: query, **opts)
      end

      # Server-Sent Events stream a stats snapshot every 2 seconds. (SSE returns the stream URL)
      def live_url(id, query = nil)
        @client.url("/api/v1/checkin/event/" + enc(id) + "/live", query)
      end

      private

      def enc(value)
        Zatabox.encode(value)
      end
    end

    # Community Verified-attendee reviews, organizer follows/subscribers and event waitlists.
    class Community
      def initialize(client)
        @client = client
      end

      # Review an event (checked-in ticket holders only; ticketCode + email prove attendance).
      def submit_review(body = nil, opts = {})
        @client.request("POST", "/api/v1/community/reviews", body: body, **opts)
      end

      # Follow an organizer (subscribe to new-event announcements).
      def follow(org_id, body = nil, opts = {})
        @client.request("POST", "/api/v1/community/orgs/" + enc(org_id) + "/follow", body: body, **opts)
      end

      # List an organizer's subscribers (organizer auth).
      def followers(org_id, query = nil, opts = {})
        @client.request("GET", "/api/v1/community/orgs/" + enc(org_id) + "/followers", query: query, **opts)
      end

      # Remove a subscriber (organizer auth).
      def remove_follower(org_id, follower_id, body = nil, opts = {})
        @client.request("DELETE", "/api/v1/community/orgs/" + enc(org_id) + "/followers/" + enc(follower_id), body: body, **opts)
      end

      # Join an event waitlist (offers fire on cancellations).
      def join_waitlist(event_id, body = nil, opts = {})
        @client.request("POST", "/api/v1/community/events/" + enc(event_id) + "/waitlist", body: body, **opts)
      end

      private

      def enc(value)
        Zatabox.encode(value)
      end
    end

    # Growth (Organizer) Comp tickets, CSV import, broadcasts and attendee tags.
    class Growth
      def initialize(client)
        @client = client
      end

      # Bulk-mint and email complimentary tickets.
      def mint_comps(event_id, body = nil, opts = {})
        @client.request("POST", "/api/v1/organizer/growth/events/" + enc(event_id) + "/comps", body: body, **opts)
      end

      # Import attendees (comp tickets) from CSV.
      def import_comps_csv(event_id, body = nil, opts = {})
        @client.request("POST", "/api/v1/organizer/growth/events/" + enc(event_id) + "/comps/import-csv", body: body, **opts)
      end

      # Email a broadcast to an event's attendees (replies thread to the organizer inbox).
      def broadcast_event(event_id, body = nil, opts = {})
        @client.request("POST", "/api/v1/organizer/growth/events/" + enc(event_id) + "/broadcast", body: body, **opts)
      end

      # Tag attendees (additive; powers broadcast filters and CRM segments).
      def add_tags(body = nil, opts = {})
        @client.request("POST", "/api/v1/organizer/growth/tags", body: body, **opts)
      end

      # Remove an attendee tag.
      def remove_tag(body = nil, opts = {})
        @client.request("DELETE", "/api/v1/organizer/growth/tags", body: body, **opts)
      end

      private

      def enc(value)
        Zatabox.encode(value)
      end
    end

    # Buyers The authenticated buyer: profile, ticket wallet, data export, refunds, reports and organizer messaging.
    class Users
      def initialize(client)
        @client = client
      end

      # Current buyer profile.
      def me(query = nil, opts = {})
        @client.request("GET", "/api/v1/users/me", query: query, **opts)
      end

      # The buyer's ticket wallet (cursor-paginated).
      def tickets(query = nil, opts = {})
        @client.request("GET", "/api/v1/users/me/tickets", query: query, **opts)
      end

      # GDPR data export one JSON download of everything on the account.
      def export(query = nil, opts = {})
        @client.request("GET", "/api/v1/users/me/export", query: query, **opts)
      end

      # Request a refund for a ticket.
      def create_refund(body = nil, opts = {})
        @client.request("POST", "/api/v1/users/me/refunds", body: body, **opts)
      end

      # File a report against an event or organizer.
      def create_report(body = nil, opts = {})
        @client.request("POST", "/api/v1/users/me/reports", body: body, **opts)
      end

      # The buyer's message threads with organizers.
      def messages(query = nil, opts = {})
        @client.request("GET", "/api/v1/users/me/messages", query: query, **opts)
      end

      # Message the organizer about a ticket (rate-limited).
      def send_ticket_message(ticket_id, body = nil, opts = {})
        @client.request("POST", "/api/v1/users/me/tickets/" + enc(ticket_id) + "/message", body: body, **opts)
      end

      private

      def enc(value)
        Zatabox.encode(value)
      end
    end

    # Courses (Learner) The authenticated buyer's online-course learner surface: enrolled courses, lesson/course completion, the exam, and the completion certificate. Course content (paid lesson media, writeups, pins) is delivered only to enrolled ticket holders; media links returned here are short-lived signed /media URLs. Buyer auth (a ticket for the course) required.
    class Courses
      def initialize(client)
        @client = client
      end

      # List the buyer's enrolled courses, each with course meta and a progress summary (started courses first). No lesson content.
      def mine(query = nil, opts = {})
        @client.request("GET", "/api/v1/courses/mine", query: query, **opts)
      end

      # Get one course's full learner payload: meta + progress + lessons (syllabus, with completed flags and signed media) or a unified content block.
      def get(event_id, query = nil, opts = {})
        @client.request("GET", "/api/v1/courses/" + enc(event_id), query: query, **opts)
      end

      # Mark a syllabus lesson complete (idempotent, zero-based index). Completing the last requirement finishes the course and may issue a certificate.
      def complete_lesson(event_id, index, body = nil, opts = {})
        @client.request("POST", "/api/v1/courses/" + enc(event_id) + "/lessons/" + enc(index) + "/complete", body: body, **opts)
      end

      # Reverse a syllabus lesson completion (does not revoke an already-issued certificate).
      def uncomplete_lesson(event_id, index, body = nil, opts = {})
        @client.request("DELETE", "/api/v1/courses/" + enc(event_id) + "/lessons/" + enc(index) + "/complete", body: body, **opts)
      end

      # Complete a unified course (unified courses only): marks the single learning unit complete.
      def complete(event_id, body = nil, opts = {})
        @client.request("POST", "/api/v1/courses/" + enc(event_id) + "/complete", body: body, **opts)
      end

      # Get the course exam to take. Correct answers and explanations are stripped server-side.
      def exam(event_id, query = nil, opts = {})
        @client.request("GET", "/api/v1/courses/" + enc(event_id) + "/exam", query: query, **opts)
      end

      # Submit the exam (body: answers:[{questionId, selectedIndex}]) for server-side grading; a pass drives completion + certificate issuance.
      def submit_exam(event_id, body = nil, opts = {})
        @client.request("POST", "/api/v1/courses/" + enc(event_id) + "/exam/submit", body: body, **opts)
      end

      # Download the issued completion certificate as a PDF (404 CERTIFICATE_NOT_ISSUED until earned).
      def certificate(event_id, query = nil, opts = {})
        @client.request("GET", "/api/v1/courses/" + enc(event_id) + "/certificate", query: query, raw: true, **opts)
      end

      private

      def enc(value)
        Zatabox.encode(value)
      end
    end

    # API keys Manage your organization's own API keys (organizer owner/admin auth).
    class Integrations
      def initialize(client)
        @client = client
      end

      # Create an API key (plaintext secret returned exactly once).
      def create_api_key(org_id, body = nil, opts = {})
        @client.request("POST", "/api/v1/organizer/integrations/org/" + enc(org_id) + "/api-keys", body: body, **opts)
      end

      # List API keys (prefixes and metadata only, never the secret).
      def list_api_keys(org_id, query = nil, opts = {})
        @client.request("GET", "/api/v1/organizer/integrations/org/" + enc(org_id) + "/api-keys", query: query, **opts)
      end

      # Update a key (rename, pause, re-scope).
      def update_api_key(org_id, key_id, body = nil, opts = {})
        @client.request("PUT", "/api/v1/organizer/integrations/org/" + enc(org_id) + "/api-keys/" + enc(key_id), body: body, **opts)
      end

      # Rotate a key's secret (new secret returned once; old one invalidated).
      def rotate_api_key(org_id, key_id, body = nil, opts = {})
        @client.request("POST", "/api/v1/organizer/integrations/org/" + enc(org_id) + "/api-keys/" + enc(key_id) + "/rotate", body: body, **opts)
      end

      # Revoke an API key.
      def delete_api_key(org_id, key_id, body = nil, opts = {})
        @client.request("DELETE", "/api/v1/organizer/integrations/org/" + enc(org_id) + "/api-keys/" + enc(key_id), body: body, **opts)
      end

      private

      def enc(value)
        Zatabox.encode(value)
      end
    end

    # Webhooks Register webhook endpoints, manage secrets, inspect and replay deliveries. (Use webhooks.verify() to validate inbound signatures.)
    class Webhooks
      def initialize(client)
        @client = client
      end

      # Create a webhook endpoint (signing secret returned exactly once).
      def create(body = nil, opts = {})
        @client.request("POST", "/api/v1/webhooks", body: body, **opts)
      end

      # List webhook endpoints.
      def list(query = nil, opts = {})
        @client.request("GET", "/api/v1/webhooks", query: query, **opts)
      end

      # Update a webhook endpoint.
      def update(id, body = nil, opts = {})
        @client.request("PUT", "/api/v1/webhooks/" + enc(id), body: body, **opts)
      end

      # Delete a webhook endpoint.
      def delete(id, body = nil, opts = {})
        @client.request("DELETE", "/api/v1/webhooks/" + enc(id), body: body, **opts)
      end

      # Send a signed test event to the endpoint.
      def test(id, body = nil, opts = {})
        @client.request("POST", "/api/v1/webhooks/" + enc(id) + "/test", body: body, **opts)
      end

      # Rotate the signing secret (new secret returned once).
      def rotate_secret(id, body = nil, opts = {})
        @client.request("POST", "/api/v1/webhooks/" + enc(id) + "/rotate-secret", body: body, **opts)
      end

      # List delivery attempts for an endpoint.
      def deliveries(id, query = nil, opts = {})
        @client.request("GET", "/api/v1/webhooks/" + enc(id) + "/deliveries", query: query, **opts)
      end

      # Replay a past delivery.
      def replay(id, body = nil, opts = {})
        @client.request("POST", "/api/v1/webhooks/deliveries/" + enc(id) + "/replay", body: body, **opts)
      end

      # List every subscribable event type (no auth).
      def catalog(query = nil, opts = {})
        @client.request("GET", "/api/v1/webhooks/catalog", query: query, **opts)
      end

      private

      def enc(value)
        Zatabox.encode(value)
      end
    end

    # ns symbol => resource class
    REGISTRY = {
      auth: Auth,
      events: Events,
      seating: Seating,
      organizer: Organizer,
      event_customization: EventCustomization,
      tickets: Tickets,
      orders: Orders,
      payments: Payments,
      checkin: Checkin,
      community: Community,
      growth: Growth,
      users: Users,
      courses: Courses,
      integrations: Integrations,
      webhooks: Webhooks,
    }.freeze
  end
end
